### ISSUE TITLE
Menu Button Toggle Navigation Rendering Issue

### ISSUE THREAD

**Issue by taschmitt** [rstudio/shinydashboard#10]
The menu button to toggle the navigation looks out of line and shows the phrase "Toggle navigation" when hovered over (see attached screen shot). I first noticed this with a webapp I'm building, so I tested it with your starter code below. It does the same thing when opened in Chrome.

![menu_button_toggle_navigation_error_image](https://cloud.githubusercontent.com/assets/10815578/6006156/e178ac92-aad5-11e4-81d0-70a1ab8e8349.jpg)

## app.R ##
library(shiny)
library(shinydashboard)
ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
)
server <- function(input, output) { }
shinyApp(ui, server)

**Comment by wch** [comment]
It looks fine for me. Can you include the output of `devtools::session_info()`?

**Comment by taschmitt** [comment]
I must be missing something because it looks fine with your example: https://jcheng.shinyapps.io/crandash/

**Comment by taschmitt** [comment]
Here is session info.

> devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, mingw32             
 ui       RStudio (0.98.1091)         
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             

Packages -------------------------------------------------------------------------------------------------------------------
 package        * version   date       source                                 
 acepack        * 1.3-3.3   2013-05-03 CRAN (R 3.1.2)                         
 aod              1.3       2012-04-10 CRAN (R 3.1.2)                         
 bitops         * 1.0-6     2013-08-17 CRAN (R 3.1.2)                         
 car              2.0-22    2014-11-18 CRAN (R 3.1.2)                         
 caTools          1.17.1    2014-09-10 CRAN (R 3.1.2)                         
 chron          * 2.3-45    2014-02-11 CRAN (R 3.1.2)                         
 cluster        * 1.15.3    2014-09-04 CRAN (R 3.1.2)                         
 colorspace     * 1.2-4     2013-09-30 CRAN (R 3.1.2)                         
 DAAG             1.20      2014-04-30 CRAN (R 3.1.2)                         
 data.table       1.9.4     2014-10-02 CRAN (R 3.1.2)                         
 DEoptimR       * 1.0-2     2014-10-19 CRAN (R 3.1.2)                         
 devtools         1.7.0     2015-01-17 CRAN (R 3.1.2)                         
 digest           0.6.7     2014-12-20 CRAN (R 3.1.2)                         
 dygraphs         0.3.3     2014-12-23 CRAN (R 3.1.2)                         
 fit.models       0.5-10    2013-02-23 CRAN (R 3.1.2)                         
 flux             0.3-0     2014-04-25 CRAN (R 3.1.2)                         
 foreign        * 0.8-61    2014-03-28 CRAN (R 3.1.2)                         
 Formula          1.1-2     2014-07-13 CRAN (R 3.1.2)                         
 ggplot2          1.0.0     2014-05-21 CRAN (R 3.1.2)                         
 gridExtra        0.9.1     2012-08-09 CRAN (R 3.1.2)                         
 gtable         * 0.1.2     2012-12-05 CRAN (R 3.1.2)                         
 heplots          1.0-12    2014-07-02 CRAN (R 3.1.2)                         
 Hmisc            3.14-6    2014-11-22 CRAN (R 3.1.2)                         
 htmltools      * 0.2.6     2014-09-08 CRAN (R 3.1.2)                         
 htmlwidgets    * 0.3.2     2014-12-09 CRAN (R 3.1.2)                         
 httpuv         * 1.3.2     2014-10-23 CRAN (R 3.1.2)                         
 httr           * 0.6.1     2015-01-01 CRAN (R 3.1.2)                         
 KMsurv           0.1-5     2012-12-03 CRAN (R 3.1.2)                         
 labeling       * 0.3       2014-08-23 CRAN (R 3.1.2)                         
 lattice          0.20-29   2014-04-04 CRAN (R 3.1.2)                         
 latticeExtra   * 0.6-26    2013-08-15 CRAN (R 3.1.2)                         
 magrittr       * 1.5       2014-11-22 CRAN (R 3.1.2)                         
 MASS             7.3-35    2014-09-30 CRAN (R 3.1.2)                         
 mime           * 0.2       2014-09-26 CRAN (R 3.1.2)                         
 multcomp       * 1.3-8     2014-12-01 CRAN (R 3.1.2)                         
 munsell        * 0.4.2     2013-07-11 CRAN (R 3.1.2)                         
 mvtnorm        * 1.0-2     2014-12-18 CRAN (R 3.1.2)                         
 nlme           * 3.1-118   2014-10-07 CRAN (R 3.1.2)                         
 nnet           * 7.3-8     2014-03-28 CRAN (R 3.1.2)                         
 openxlsx         2.2.1     2014-10-18 CRAN (R 3.1.2)                         
 pcaPP          * 1.9-60    2014-10-22 CRAN (R 3.1.2)                         
 plyr           * 1.8.1     2014-02-26 CRAN (R 3.1.2)                         
 png              0.1-7     2013-12-03 CRAN (R 3.1.2)                         
 polspline      * 1.1.9     2013-11-20 CRAN (R 3.1.2)                         
 proto          * 0.3-10    2012-12-22 CRAN (R 3.1.2)                         
 quantreg       * 5.05      2013-09-23 CRAN (R 3.1.2)                         
 R6             * 2.0.1     2014-10-29 CRAN (R 3.1.2)                         
 randomForest     4.6-10    2014-07-17 CRAN (R 3.1.2)                         
 rattle           3.3.0     2014-09-07 CRAN (R 3.1.2)                         
 RColorBrewer   * 1.1-2     2014-12-07 CRAN (R 3.1.2)                         
 Rcpp           * 0.11.3    2014-09-29 CRAN (R 3.1.2)                         
 RCurl          * 1.95-4.5  2014-12-06 CRAN (R 3.1.2)                         
 reshape2         1.4.1     2014-12-06 CRAN (R 3.1.2)                         
 RJSONIO        * 1.3-0     2014-07-28 CRAN (R 3.1.2)                         
 rms              4.2-1     2014-09-19 CRAN (R 3.1.2)                         
 robust           0.4-16    2014-05-18 CRAN (R 3.1.2)                         
 robustbase       0.92-2    2014-11-22 CRAN (R 3.1.2)                         
 rpart          * 4.1-8     2014-03-28 CRAN (R 3.1.2)                         
 rrcov            1.3-8     2014-12-02 CRAN (R 3.1.2)                         
 rstudio        * 0.98.1091 2014-11-14 local                                  
 rstudioapi     * 0.2       2014-12-31 CRAN (R 3.1.2)                         
 sandwich       * 2.3-2     2014-08-24 CRAN (R 3.1.2)                         
 scales           0.2.4     2014-04-22 CRAN (R 3.1.2)                         
 shiny            0.10.2.2  2014-12-08 CRAN (R 3.1.2)                         
 shinydashboard   0.2.1     2015-02-02 Github (rstudio/shinydashboard@74e8d4d)
 snow             0.3-13    2013-09-27 CRAN (R 3.1.2)                         
 snowfall         1.84-6    2013-12-18 CRAN (R 3.1.2)                         
 SparseM          1.05      2014-07-14 CRAN (R 3.1.2)                         
 stringr        * 0.6.2     2012-12-06 CRAN (R 3.1.2)                         
 survAUC          1.0-5     2012-09-04 CRAN (R 3.1.2)                         
 survival         2.37-7    2014-01-22 CRAN (R 3.1.2)                         
 TH.data        * 1.0-5     2014-11-24 CRAN (R 3.1.2)                         
 xtable         * 1.7-4     2014-09-12 CRAN (R 3.1.2)                         
 zoo            * 1.7-11    2014-02-27 CRAN (R 3.1.2)

**Comment by taschmitt** [comment]
Just had my buddy run it on his computer. It looks fine on his, so it something with my computer. I tried it in several browsers, etc. and renders the same, so not really sure what the issue is. Weird that your Streaming CRAN data webapp renders correctly on my computer.

**Comment by wch** [comment]
I think you need to update your version of Shiny to 0.11, with `install.packages('shiny')`. I suggest starting from a clean R session before running that.

That version should have automatically been installed when you ran `install_github('rstudio/shinydashboard')`, but it's possible that there's a problem when doing that on Windows.

**Comment by taschmitt** [comment]
Just saw that. Sorry about wasting your time.
