### ISSUE TITLE
DropDown Menu TaskItem value by param

### ISSUE THREAD

**Issue by mahdsip** [rstudio/shinydashboard#103]
i couldnt find a way to assing a param value to TaskItem/Value, just hardcoded, is it possible to do it?

**Comment by wch** [comment]
Sorry, I don't understand the question you're trying to ask. Can you be more detailed?

**Comment by mahdsip** [comment]
Sure, 
 i have this
 dropdownMenu(type = "tasks",badgeStatus = "success",taskItem(value = 82.7, color = "yellow")

I wonder if there is way of assigning value attribute to a variable calculated from server.r

Thanks!

**Comment by wch** [comment]
You should be able to use `dropdownMenuOutput` in the UI, and generate the `dropdownMenu` on the server side. See http://rstudio.github.io/shinydashboard/structure.html#dynamic-content
