### ISSUE TITLE
Is it possible to use other adminlte themes with shinydashboard?

### ISSUE THREAD

**Issue by picardilly** [rstudio/shinydashboard#105]
Hi

I'm wondering whether it is possible to use other adminlte themes with shinydashboard?

For example:
https://wrapbootstrap.com/theme/homer-responsive-admin-theme-WB055J451

If it doesn't work out of box, could you please describe the steps needed for this customization?

Thank you for this wonderful package.

Marc

**Comment by wch** [comment]
Hi, I just took a look at the HTML and CSS used in their example, and it looks like it's very different -- I think it would require re-writing most of the code in shinydashboard.
