### ISSUE TITLE
how to make color of box title bar consistent with dashboardPage skin selection?

### ISSUE THREAD

**Issue by ghost** [rstudio/shinydashboard#109]
When I use skin="red" in the dashboardPage(), ideally, box title bar color should be the same color theme.  So instead of having blue as the box title bar color while skin is set to "red", it should be either red or reddish color.  Any suggestion how to achieve this?  thanks.

**Comment by wch** [comment]
Sorry, AdminLTE (which shinydashboard is built on) doesn't support this. You would have to set the color of each box manually.
