### ISSUE TITLE
Image in sidebarUserPanel

### ISSUE THREAD

**Issue by joelgombin** [rstudio/shinydashboard#11]
The `sidebarUserPanel` function has only one `name` argument, but its source code refers to an image:

```r
sidebarUserPanel <- function(name) {
  div(class = "user-panel",
    div(class = "pull-left image",
      img(src = "foo.png", class = "img-circle", alt = "User Image")
    ),
    div(class = "pull-left info",
      p(paste("Hello,", name)),
      a(href = "#", shiny::icon("circle", class = "text-success"), "Online")
    )
  )
}
```

Consequently, a missing image appears. I guess the image src should be an argument of the `sidebarUserPanel` function, probably with a meaningful default.

**Comment by wch** [comment]
Oops, that was left over from testing. I've pushed a fix for it.

**Comment by wch** [comment]
Another oops - it looks like I didn't really fix this the first time. But it should work now.
