### ISSUE TITLE
Separate presentation from content

### ISSUE THREAD

**Issue by airstrike** [rstudio/shinydashboard#111]
I know this is a pretty broad issue, but I can't help but think that shinydashboard would benefit from separating presentation from content. If you think about it, the `ui` component of shiny actually includes elements that go far beyond the definition of user interface. I come from a Python/Django background, and [the concept of splitting up models, views and templates](https://docs.djangoproject.com/en/1.9/faq/general/#django-appears-to-be-a-mvc-framework-but-you-call-the-controller-the-view-and-the-view-the-template-how-come-you-don-t-use-the-standard-names) (or [models, templates, and views, in other contexts](http://lukeplant.me.uk/blog/posts/mvc-is-not-a-helpful-analogy-for-django/)) is incredibly powerful.

The actual definition of how views and templates would work in shiny/shinydashboard is prone to significant bikeshedding, so I won't get into it, but I argue that adopting a paradigm in which these roles are well defined and detached would make complex applications much easier to maintain.

Has this been considered at all? Is it a valid proposal? If so, what are the steps we need to move in that direction?

**Comment by jcheng5** [comment]
I think of the shiny server function being the equivalent of django's View, and the ui object being the equivalent of the Template. I mean, if you print the ui object at the console, you will see that it is *literally* just HTML. The Model would be your data and the non-Shiny-specific functions and objects you use to manipulate them.

What do you see as being the elements of ui that you could split up?
