### ISSUE TITLE
verbatimTextOutput() error

### ISSUE THREAD

**Issue by Rahul15** [rstudio/shinydashboard#117]
Hi,

![screenshot from 2016-01-26 19 32 08](https://cloud.githubusercontent.com/assets/2969657/12582688/9a89bdc2-c464-11e5-9db6-11fb115abe1e.png)

SessionInfo

R version 3.2.1 (2015-06-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_IN       LC_NUMERIC=C         LC_TIME=en_IN       
 [4] LC_COLLATE=en_IN     LC_MONETARY=en_IN    LC_MESSAGES=en_IN   
 [7] LC_PAPER=en_IN       LC_NAME=C            LC_ADDRESS=C        
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_IN LC_IDENTIFICATION=C 

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] mixOmics_5.1.2       MASS_7.3-44          caret_6.0-52        
 [4] beanplot_1.2         RColorBrewer_1.1-2   corrplot_0.73       
 [7] DMwR_0.4.1           fields_8.2-1         maps_2.3-11         
[10] spam_1.0-1           mice_2.22            Rcpp_0.12.1         
[13] cluster_2.0.3        Hmisc_3.17-0         ggplot2_1.0.1       
[16] Formula_1.2-1        survival_2.38-3      lattice_0.20-33     
[19] shinythemes_1.0.1    dygraphs_0.4.5       shinydashboard_0.5.1
[22] shiny_0.12.2        

loaded via a namespace (and not attached):
 [1] jsonlite_0.9.17     splines_3.2.1       foreach_1.4.2      
 [4] ellipse_0.3-8       gtools_3.5.0        TTR_0.23-0         
 [7] stats4_3.2.1        latticeExtra_0.6-26 quantreg_5.19      
[10] digest_0.6.8        randomForest_4.6-10 minqa_1.2.4        
[13] colorspace_1.2-6    htmltools_0.2.6     httpuv_1.3.3       
[16] Matrix_1.2-2        plyr_1.8.3          pheatmap_1.0.7     
[19] BradleyTerry2_1.0-6 SparseM_1.7         xtable_1.7-4       
[22] scales_0.3.0        gdata_2.17.0        MatrixModels_0.4-1 
[25] brglm_0.5-9         lme4_1.1-9          mgcv_1.8-7         
[28] car_2.1-0           ROCR_1.0-7          nnet_7.3-11        
[31] pbkrtest_0.4-2      quantmod_0.4-5      proto_0.3-10       
[34] magrittr_1.5        mime_0.4            nlme_3.1-122       
[37] gplots_2.17.0       xts_0.9-7           foreign_0.8-66     
[40] class_7.3-14        tools_3.2.1         stringr_1.0.0      
[43] munsell_0.4.2       pls_2.5-0           caTools_1.17.1     
[46] nloptr_1.0.4        iterators_1.0.7     htmlwidgets_0.5    
[49] igraph_1.0.1        labeling_0.3        bitops_1.0-6       
[52] gtable_0.1.2        codetools_0.2-14    abind_1.4-3        
[55] reshape2_1.4.1      R6_2.1.1            gridExtra_2.0.0    
[58] zoo_1.7-12          KernSmooth_2.23-15  stringi_0.5-5      
[61] parallel_3.2.1      rgl_0.95.1367       rpart_4.1-10       
[64] acepack_1.3-3.3   

why it is showing the tr td ????

**Comment by dmpe** [comment]
please add reproducible example @Rahul15

**Comment by Rahul15** [comment]
ui.R

library(shiny)
library(shinydashboard)


#Dashboard Header
 
 header <- dashboardHeader( title="Upload Data", titleWidth=1000,

                            #tags$head(
                            #          tags$link(  HTML( '<title>Data Upload>')
                            #          )
                            #)
                            dropdownMenu(type = "messages", 
                                        messageItem(
                                                    from = "Dept",
                                                    message = "Under construction"

                                        )
                            )

                          )

#Sidebar Panel
 Sidebar <- dashboardSidebar(width=200,
                            sidebarMenu(
                                        
                                        menuItem("Upload Data", tabName="filetable", icon= icon("upload"))
					
                                        
                            )
 )


#Dashboard Body
 body <- dashboardBody(
                        tags$head(tags$style(HTML('
                                                  .main-header .logo {
                                                                      font-family: "Georgia", Times, "Times New Roman", serif;
                                                                     font-weight: bold;
                                                                      font-size: 34px;
                                                                      }'
                                              )
                                  ) 
                        ),
                        tags$head(
                                  tags$link(rel = "stylesheet", type = "text/css", href = "custom.css"),
                                  tags$style(HTML( '
                                                .main-header .logo {
                                                                     font-family: "Georgia", Times, "Times New Roman", serif;
                                                                     font-weight: bold;
                                                                     font-size: 34px;
                                                                     }' )
                                  )
                        ),
                        tabItems(
                                
                                tabItem(tabName="filetable",
                                        fluidRow(
                                                box(title="Data Input", status="primary", solidHeader=TRUE,
                                                    collapsible=TRUE,
                                                    radioButtons("dataInput", "", choices=list("Load sample data"=1,"Upload file"=2,"Paste data"=3), selected=1),
                                                    conditionalPanel(condition="input.dataInput=='1'",
                                                                    h5("Selected Data Input")
                                                    ),
                                                    conditionalPanel(condition="input.dataInput=='2'",
                                                                    h5("Upload delimited text file: "),
                                                                    fileInput("upload", "", multiple = FALSE),
                                                                    radioButtons("fileSepDF", "Delimiter:", list("Comma"=1,"Tab"=2,"Semicolon"=3)),
                                                                                                                        ),
                                                    conditionalPanel(condition="input.dataInput=='3'",
                                                                    h5("Paste data below:"),
                                                                    tags$textarea(id="myData", rows=10, cols=100, ""), br(),
                                                                    actionButton('clearText_button','Clear data'),
                                                                    radioButtons("fileSepP", "Separator:", list("Comma"=1,"Tab"=2,"Semicolon"=3))
                                                    ), width=12
                                                ),
                                                box(title="Data", status="primary", solidHeader=TRUE, collapsible=TRUE,
                                                    verbatimTextOutput("filetable"), width=12)
                                        )
                                )
				
                        )
)

ui <- dashboardPage(
                    header,
                    Sidebar,
                    body,
                    skin="blue"
)








server.R

library(shiny)
library(shinythemes)
library(shinydashboard)


server <- function(input, output, session) {
    
  dataM <- reactive({
                    if(input$dataInput==1){
                                           data <- read.table("Sample.csv", sep=",", header=TRUE, fill=TRUE)      
                    } 
                    else if(input$dataInput==2){
                                                inFile <- input$upload
                      # Avoid error message while file is not uploaded yet
                                                if (is.null(input$upload))  {return(NULL)}
                      # Get the separator
                                                mySep <- switch(input$fileSepDF, '1'=",",'2'="\t",'3'=";", '4'="") #list("Comma"=1,"Tab"=2,"Semicolon"=3)
                                                if(file.info(inFile$datapath)$size <= 10485800){
                                                                                                data<-read.table(inFile$datapath, sep=mySep, header=TRUE, fill=TRUE)
                                                } 
                                                else print("File is more than 10MB size will not be uploaded.")
                    } 
                    else { 
                                                if(is.null(input$myData)) {return(NULL)} 
                                                tmp <- matrix(strsplit(input$myData, "\n")[[1]])
                                                mySep <- switch(input$fileSepP, '1'=",",'2'="\t",'3'=";")
                                                myColnames<-strsplit(tmp[1], mySep)[[1]]
                                                data <- matrix(0, length(tmp)-1, length(myColnames))
                                                colnames(data)<-myColnames
                                                for(i in 2:length(tmp)){
                                                myRow <- as.numeric(strsplit(paste(tmp[i],mySep,mySep,sep=""), mySep)[[1]])
                                                data[i-1,] <- myRow[-length(myRow)]
                                                }
                                                data <- data.frame(data)    
                    }
                    return(data)
  })


output$filetable <- renderTable({
                                
                                print(nrow(dataM()))
                                if(nrow(dataM()) < 500){
                                                        return(dataM())
                                } 
                                else {
                                      return(dataM()[1:100,])
                                }
                                #dataM()
})



}



SessionInfo()

locale:
 [1] LC_CTYPE=en_IN       LC_NUMERIC=C         LC_TIME=en_IN       
 [4] LC_COLLATE=en_IN     LC_MONETARY=en_IN    LC_MESSAGES=en_IN   
 [7] LC_PAPER=en_IN       LC_NAME=C            LC_ADDRESS=C        
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_IN LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinydashboard_0.5.1 shiny_0.12.2        

loaded via a namespace (and not attached):
[1] R6_2.1.1        htmltools_0.2.6 Rcpp_0.12.1     digest_0.6.8   
[5] xtable_1.7-4    httpuv_1.3.3    mime_0.4

**Comment by dmpe** [comment]
@Rahul15 please provide sample.csv, either here or over my email.
in your code, i had to add selected=NULL as otherwise it would not run, see

```
library(shiny)
library(shinydashboard)
library(shinythemes)
#Dashboard Header

header <- dashboardHeader(
  title = "Upload Data",
  titleWidth = 1000,

  #tags$head(
  #          tags$link(  HTML( '<title>Data Upload>')
  #          )
  #)
  dropdownMenu(type = "messages",
               messageItem(from = "Dept",
                           message = "Under construction"))

)

#Sidebar Panel
sidebar <- dashboardSidebar(width = 200,
                            sidebarMenu(menuItem(
                              "Upload Data", tabName = "filetable", icon = icon("upload")
                            )))

#Dashboard Body
body <- dashboardBody(
  tags$head(tags$style(
  HTML(
    '
    .main-header .logo {
    font-family: "Georgia", Times, "Times New Roman", serif;
    font-weight: bold;
    font-size: 34px;
    }'
  )
  )),
  tags$head(
    tags$link(rel = "stylesheet", type = "text/css", href = "custom.css"),
    tags$style(
      HTML(
        '
        .main-header .logo {
        font-family: "Georgia", Times, "Times New Roman", serif;
        font-weight: bold;
        font-size: 34px;
        }'
    )
      )
      ),
  tabItems(tabItem(tabName = "filetable",
                   fluidRow(
                     box(
                       title = "Data Input",
                       status = "primary",
                       solidHeader = TRUE,
                       collapsible = TRUE,
                       radioButtons(
                         "dataInput",
                         "",
                         choices = list(
                           "Load sample data" = 1,
                           "Upload file" = 2,
                           "Paste data" = 3
                         ),
                         selected = 1
                       ),
                       conditionalPanel(condition = "input.dataInput=='1'",
                                        h5("Selected Data Input")),
                       conditionalPanel(
                         condition = "input.dataInput=='2'",
                         h5("Upload delimited text file: "),
                         fileInput("upload", "", multiple = FALSE),
                         radioButtons(
                           "fileSepDF",
                           "Delimiter:",
                           list(
                             "Comma" = 1,
                             "Tab" = 2,
                             "Semicolon" = 3
                           )
                         ), selected = NULL
                       ),
                       conditionalPanel(
                         condition = "input.dataInput=='3'",
                         h5("Paste data below:"),
                         tags$textarea(id = "myData", rows = 10, cols =
                                         100, ""),
                         br(),
                         actionButton('clearText_button', 'Clear data'),
                         radioButtons(
                           "fileSepP",
                           "Separator:",
                           list(
                             "Comma" = 1,
                             "Tab" = 2,
                             "Semicolon" = 3
                           )
                         )
                       ),
                       width = 12
                     ),
                     box(
                       title = "Data",
                       status = "primary",
                       solidHeader = TRUE,
                       collapsible = TRUE,
                       verbatimTextOutput("filetable"),
                       width = 12
                     )
                   ))))

ui <- dashboardPage(header,
                    Sidebar,
                    body,
                    skin = "blue")


server <- function(input, output, session) {
  dataM <- reactive({
    if (input$dataInput == 1) {
      data <- read.table("Sample.csv",
                         sep = ",",
                         header = TRUE,
                         fill = TRUE)

    }
    else if (input$dataInput == 2) {
      inFile <- input$upload
      # Avoid error message while file is not uploaded yet
      if (is.null(input$upload)) {
        return(NULL)
      }
      # Get the separator
      mySep <-
        switch(
          input$fileSepDF,
          '1' = ",",
          '2' = "\t",
          '3' = ";",
          '4' = ""
        ) #list("Comma"=1,"Tab"=2,"Semicolon"=3)
      if (file.info(inFile$datapath)$size <= 10485800) {
        data <- read.table(
          inFile$datapath,
          sep = mySep,
          header = TRUE,
          fill = TRUE
        )
      }
      else
        print("File is more than 10MB size will not be uploaded.")
    }
    else {
      if (is.null(input$myData)) {
        return(NULL)
      }
      tmp <- matrix(strsplit(input$myData, "\n")[[1]])
      mySep <- switch(input$fileSepP,
                      '1' = ",",
                      '2' = "\t",
                      '3' = ";")
      myColnames <- strsplit(tmp[1], mySep)[[1]]
      data <- matrix(0, length(tmp) - 1, length(myColnames))
      colnames(data) <- myColnames
      for (i in 2:length(tmp)) {
        myRow <-
          as.numeric(strsplit(paste(tmp[i], mySep, mySep, sep = ""), mySep)[[1]])
        data[i - 1, ] <- myRow[-length(myRow)]
      }
      data <- data.frame(data)

    }
    return(data)
  })

  output$filetable <- renderTable({
    print(nrow(dataM()))
    if (nrow(dataM()) < 500) {
      return(dataM())
    }
    else {
      return(dataM()[1:100, ])
    }
    #dataM()

  })

}

shinyApp(ui, server)

```

**Comment by wch** [comment]
Can you please make it a *minimal* example?

**Comment by Rahul15** [comment]
ui.R

library(shiny)
library(shinydashboard)

#Dashboard Header 
 header <- dashboardHeader( title="Upload Data", titleWidth=1000)

#Sidebar Panel
 Sidebar <- dashboardSidebar(width=200,
                            sidebarMenu(
                                        
                                        menuItem("Upload Data", tabName="filetable", icon= icon("upload"))                                      
                            )
 )
#Dashboard Body
 body <- dashboardBody(
                   tabItems(
                                
                                tabItem(tabName="filetable",
                                        fluidRow(
                                                box(title="Data Input", status="primary", solidHeader=TRUE,
                                                    collapsible=TRUE,
                                                    radioButtons("dataInput", "", choices=list("Load sample data"=1,"Upload file"=2,"Paste data"=3), selected=1),
                                                    conditionalPanel(condition="input.dataInput=='1'",
                                                                    h5("Selected Data Input")
                                                    ),
                                                    conditionalPanel(condition="input.dataInput=='2'",
                                                                    h5("Upload delimited text file: "),
                                                                    fileInput("upload", "", multiple = FALSE),
                                                                    radioButtons("fileSepDF", "Delimiter:", list("Comma"=1,"Tab"=2,"Semicolon"=3))
                                                                                                                        ),
                                                    conditionalPanel(condition="input.dataInput=='3'",
                                                                    h5("Paste data below:"),
                                                                    tags$textarea(id="myData", rows=10, cols=100, ""), br(),
                                                                    actionButton('clearText_button','Clear data'),
                                                                    radioButtons("fileSepP", "Separator:", list("Comma"=1,"Tab"=2,"Semicolon"=3))
                                                    ), width=12
                                                ),
                                                box(title="Data", status="primary", solidHeader=TRUE, collapsible=TRUE,
                                                    verbatimTextOutput("filetable"), width=12)
                                        )
                                )
        
                        )     
                        
)

ui <- dashboardPage(
                    header,
                    Sidebar,
                    body,
                    skin="blue"
)



server.R file



library(shiny)
library(shinythemes)
library(shinydashboard)


server <- function(input, output, session) {
    
dataM <- reactive({
                    if(input$dataInput==1){
                                           data <- read.table("Sample.csv", sep=",", header=TRUE, fill=TRUE)      
                    } 
                    else if(input$dataInput==2){
                                                inFile <- input$upload
                 
                                                if (is.null(input$upload))  {return(NULL)}
                    
                                                mySep <- switch(input$fileSepDF, '1'=",",'2'="\t",'3'=";", '4'="")
                                                if(file.info(inFile$datapath)$size <= 10485800){
                                                data<-read.table(inFile$datapath, sep=mySep, header=TRUE, fill=TRUE)
                                                } 
                                                else print("File is more than 10MB aded.")
                    } 
                    else { 
                                                if(is.null(input$myData)) {return(NULL)} 
                                                tmp <- matrix(strsplit(input$myData, "\n")[[1]])
                                                mySep <- switch(input$fileSepP, '1'=",",'2'="\t",'3'=";")
                                                myColnames<-strsplit(tmp[1], mySep)[[1]]
                                                data <- matrix(0, length(tmp)-1, length(myColnames))
                                                colnames(data)<-myColnames
                                                for(i in 2:length(tmp)){
                                                myRow <- as.numeric(strsplit(paste(tmp[i],mySep,mySep,sep=""), mySep)[[1]])
                                                data[i-1,] <- myRow[-length(myRow)]
                                                }
                                                data <- data.frame(data)    
                    }
                    return(data)
  })


output$filetable <- renderTable({
                                
                                print(nrow(dataM()))
                                if(nrow(dataM()) < 500){
                                                        return(dataM())
                                } 
                                else {
                                      return(dataM()[1:100,])
                                }
                                #dataM()
})



}




I think this is minimal code. For Sample.csv file use any .csv file.
session-info will be similar as above.

**Comment by wch** [comment]
@Rahul15 Please see the [Markdown formatting guide](https://guides.github.com/features/mastering-markdown/) to make the code appear correctly.

**Comment by dmpe** [comment]
Update your xtable package first from cran @Rahul15 https://cran.r-project.org/web/packages/xtable/index.html if you can (and test it too)

**Comment by wch** [comment]
@Rahul15 your problem is that you're using a `verbatimTextOutput` in the UI with a `renderTable` in the server code. The UI should have `tableOutput`.

**Comment by Rahul15** [comment]
Thanks  @wch it worked.

But the problem is that I have to display 100 of columns from the csv file into the box() and only few of the column were able to display in the tableOutput().

Is there any way to do that ??
