### ISSUE TITLE
status 'default'

### ISSUE THREAD

**Issue by msenn** [rstudio/shinydashboard#118]
Currently, the status argument takes 5 values (`?validStatuses`). However, AdminLTE supports a sixth status (default) producing gray boxes [(https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#component-box)](https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#component-box). The class 'box-default' needs to be set to get the gray solid box.

**Comment by bborgesr** [comment]
Sorry for the very late reply. The "default" look is given by `status = NULL`, which is the default argument value for `box()`. So, no changes are required.
