### ISSUE TITLE
Slider styles

### ISSUE THREAD

**Issue by jackolney** [rstudio/shinydashboard#122]
Hi Winston,

This is more of a feature request / query rather than an issue.

Just playing around with the dashboard and custom sliders, is it possible to style the sliders as in AdminLTE (https://almsaeedstudio.com/themes/AdminLTE/pages/UI/sliders.html) without a whole bunch of custom css and div tags? Doesn't look as though anything to do with sliders is imported in the AdminLTE.min.css file? Wanted to check anyway.

Thanks, and thanks for all the work on this package, it is incredible!

**Comment by bborgesr** [comment]
Sorry for the very late reply. All of the sliders in the first box (in the link you posted) use the ion range slider JS library, which is the same that Shiny uses, so you can recreate them in Shiny fairly easily.

<details>
  <summary>Ion range slider example app (using the same sliders as <a href="https://almsaeedstudio.com/themes/AdminLTE/pages/UI/sliders.html">AdminLTE</a>)</summary>

  ```r
  library(shiny)
  library(shinydashboard)

  ui <- dashboardPage(
    dashboardHeader(title = "Sliders"),
    dashboardSidebar(),
    dashboardBody(
      box("Ion Slider", status = "primary", width = 12,
        br(),
        br(),
        fluidRow(
          column(6, 
            sliderInput("is1", NULL, 0, 5000, c(1000, 4000), 
              pre = "$", ticks = FALSE)
          ),
          column(6, 
            sliderInput("is2", NULL, 10, 100, c(10, 100), 
              post = " €", step = 100, ticks = FALSE)
          )
        ),
        fluidRow(
          column(6, 
            sliderInput("is3", NULL, 0, 10, 0, 
              post = " mm", step = 0.1, ticks = FALSE)
          ),
          column(6, 
            sliderInput("is4", NULL, -50, 50, 0, 
              post = "º", ticks = FALSE)
          )
        ),
        fluidRow(
          column(12, 
            sliderInput("is5", NULL, 10, 100, 10, 
              post = " light years", step = 100, ticks = FALSE)
          )
        )
      )
    )
  )

  server <- function(input, output, session) {}
  shinyApp(ui, server)
  ```
</details>
<br>

Unfortunately, all the sliders in the second box use [another plugin](https://github.com/seiyria/bootstrap-slider) that neither Shiny nor Shinydashboard have. So it would take quite some effort  on your part to get those "out of the box." It'd be much easier to use some css rules to alter the look of the default ion range sliders.

Let me know if there was more to your question and we can re-open the issue.
