### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dcabanillas** [rstudio/shinydashboard#123]
I have copied the examples from https://rstudio.github.io/shinydashboard/get_started.html but I have the following error:

Loading required package: shiny
Warning: package ‘shiny’ was built under R version 3.2.3

Listening on http://127.0.0.1:3200
Warning: Error in serverFuncSource: server.R returned an object of unexpected type: list
Stack trace (innermost first):
    1: shiny::runApp
Error in serverFuncSource() : 
  server.R returned an object of unexpected type: list

**Comment by dcabanillas** [comment]
I have installed the R versions 3.2.3 but I have the same error.

Listening on http://127.0.0.1:4123
Warning: Error in serverFuncSource: server.R returned an object of unexpected type: list
Stack trace (innermost first):
    1: shiny::runApp
Error in serverFuncSource() : 
  server.R returned an object of unexpected type: list

However, if I publish to Server the shiny application works.

**Comment by wch** [comment]
It sounds like you are putting the content that should go in app.R, in server.R instead. Please read the text carefully, with attention to what it says about single-file apps. Also see the link to the single-file app article.
