### ISSUE TITLE
downloadButton breaks if nested under menuItem

### ISSUE THREAD

**Issue by tleja** [rstudio/shinydashboard#126]
Hi, I would like to include a `downloadButton` **under** `menuItem` in sidebar. However, when clicked, it opens a new session in a second tab (Google Chrome) instead of downloading the data. See the example below.

```
require(shiny)
require(shinydashboard)

ui <- dashboardPage(
    dashboardHeader(title = "Download button test"),
    dashboardSidebar( 
        sidebarMenu(
            menuItem("Save results", icon=icon('download'),
                 downloadButton("save_button", "Click here to save results ...")
            )
        )
    ),
    dashboardBody(
        plotOutput("results")
    )
)

server <- function(input, output) {

    data <- reactive({ 
        rnorm(100) 
    })

    output$results <- renderPlot({
        hist(data())
    })

    output$save_button <- downloadHandler(
        filename = function() {
            paste0('data-', Sys.time(), '.csv')
        },
        content = function(file) {
            write.csv(data(), file)
        }
    )
}

shinyApp(ui, server)
```

Interestingly, the `downloadButton` works if it is placed **outside** of the `menuItem`:

```
ui <- dashboardPage(
    dashboardHeader(title = "Download button test"),
    dashboardSidebar( 
        sidebarMenu(
            menuItem("Save results", icon=icon('download')),
            downloadButton("save_button", "Click here to save results ...")
        )
    ),
    dashboardBody(
        plotOutput("results")
    )
)

shinyApp(ui, server)
```

Any suggestions would be much appreciated!

**Comment by tleja** [comment]
OK, I found a solution [here](https://groups.google.com/forum/#!topic/shiny-discuss/TWikVyknHYA). The line below is needed after `downloadHandler` is defined in `server` function:

```
outputOptions(output, "save_button", suspendWhenHidden=FALSE)
```
It seems the `downloadButton` is being suspended when hidden underneath the `menuItem`. Switching off `suspendWhenHidden` in `outputOptions` allows it to work properly in this case.

**Comment by bborgesr** [comment]
Sorry for the very late reply. Your fix is great and there's no problem keeping it. However, as of 1d21267dc23595650cb30a363056af37784ff029, this has been fixed and your original code works. Note that this fix is in the development version of shinydashboard (installed with `devtools::install_github("rstudio/shinydashboard")`), but not in the CRAN version yet (installed with `install.packages("shinydashboard")`). We plan on releasing to CRAN within the next couple of weeks.

**Comment by tleja** [comment]
That's great news! Thank you.
