### ISSUE TITLE
Programmatically select sidebar tab

### ISSUE THREAD

**Issue by pan0ramic** [rstudio/shinydashboard#13]
With the addition of `id` to the `sidebarMenu`, would it be possible to implement a way to programmatically select a sidebar tab?

For instance, it would be great if you could do something like:
 `updateTabsetPanel(session, sidebar.id, selected = a.sidebar.tab)`

**Comment by wch** [comment]
Good idea; I've implemented it. See `?updateTabItems` for an example.

**Comment by pan0ramic** [comment]
Awesome, thanks so much! I will be rolling this out in production today.

**Comment by wch** [comment]
Great!
