### ISSUE TITLE
fluidePage don't work on shinydashboard

### ISSUE THREAD

**Issue by dchahor** [rstudio/shinydashboard#136]
Hey!
I just have an issue when I want to have a fluid page on the dashboard it's not working, thanks in advance ?

#ui
library(shiny)
library(shinydashboard)

  
  dashboardPage(skin="purple", fluidPage(
  dashboardHeader(title = "NEWSTAT",titleWidth = 250),
  dashboardSidebar(width = 250,sidebarMenu(menuItem("Uploader vos données", tabName = "lecture", icon = icon("database"),
                            menuSubItem(selected = NULL,icon = NULL,fileInput('file1',label=NULL,
                             accept=c('text/csv', 
                                      'text/comma-separated-values,text/plain', 
                                      '.csv','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','xlsx'))),
                            checkboxInput('header', 'Entête', TRUE),
                            radioButtons('sep', 'Séparateur',
                                c(Virgule=',',
                                  `Point virgule`=';',
                                  Tabulation='\t'),
                                ','),
                   radioButtons('na', 'Symbole des valeurs manquantes',
                                c(`Cellule vide`=' ',
                                  `NA`='NA',
                                  `?`='\t'),
                                ' ')),
                  
                  menuItem("Votre Rapport",tabName = "Decouverte",icon = icon("cloud-download"),selected = TRUE, badgeLabel = "ici", badgeColor = "red")
                  
                  )),
  dashboardBody(tags$head(tags$style(HTML('body {
                                          font-family: "Source Sans Pro",sans-serif;
                                          font-size: 14px;
                                          line-height: 1.45;
                                          color: #3f3f3f;
                                          }'))),fluidPage(tabsetPanel(type="tabs",
                                  tabPanel(strong("Tableur"), dataTableOutput("table")), 
                                  tabPanel(strong("Valeurs manquantes"),br(),h5(strong("Exploration des valeurs manquantes")),box(title="Tableau des valeurs manquantes",status="warning",width=NULL,h5(helpText("La table suivante résume le pourcentage de valeurs manquantes par colonne (variable) dans toute la base de données.")),tableOutput("na_table1")),fluidRow(box(title="Histogramme",width=10,status = "danger",collapsible = TRUE,plotOutput('plot_na',width = "500px", height = "300px"))),tags$div(),h5(strong("Traitement des valeurs manquantes")),
                                           fluidRow(column(width=6,box(width=NULL,status = "info",title = "Remarques",textOutput("na_text1"),htmlOutput("na_text2"))),column(width=4,box(
                                             width = NULL,status = "warning",collapsed=TRUE,title = "Pourcentage toléré",sliderInput("missinrate",label = "", min = 0,max = 70, value = 9)))),fluidRow(box(width=6,title = "Procéder à un traitement simple de la base de donnée?",status = "success",actionButton("treat","Traitement"),h4(htmlOutput("warning_na"))),infoBoxOutput("countna"))
                                           #,helpText('Cette table est provisoire, cest pour montrer que le traitement a bien marché')
                                           #,tableOutput("na_table2")
                                  ),
                                  tabPanel(strong("Résumer"), box(tableOutput("summary"),width=NULL,status = "info",title = "Aperçu")), 
                                  tabPanel(strong("Visualiser"),br(),box(title = "Analyse univariée",collapsible = TRUE, status = "primary",plotOutput("hist")),box(
                                    title = "Variable", status = "warning",width=4,collapsible = TRUE,selectInput("columname", "Sélectionner votre variable",choices = NULL)),
                                    box(title = "Boite de contrôle", status = "info",collapsed = TRUE,collapsible = TRUE,width=4,sliderInput("bins",
                                                "Nombre de batôn",
                                                min = 1,
                                                max = 50,
                                                value = 30),uiOutput("slider"),h5("Les labels ne sont pas lisibles?"),
                                    checkboxInput("fliplab", "Aménager le graphique", value = FALSE, width = NULL)))
  )))
)

**Comment by wch** [comment]
You shouldn't use `fluidPage()` in there. See http://rstudio.github.io/shinydashboard/structure.html#structure-overview
