### ISSUE TITLE
Issue with valueBoxOutput

### ISSUE THREAD

**Issue by happyshows** [rstudio/shinydashboard#14]
Code on guide page doesn't work in 0.2.2
http://rstudio.github.io/shinydashboard/structure.html#valuebox

valueBoxOutput("progressBox")
Error in shiny::uiOutput(outputId, class = paste0("col-sm-", width)) : 
  unused argument (class = paste0("col-sm-", width))

sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] shinydashboard_0.2.2 DiagrammeR_0.4       shiny_0.11          
 [4] ND3_0.1.2            stringr_0.6.2        igraph_0.7.999-125  
 [7] lazyeval_0.1.10.9000 tidyr_0.1            dplyr_0.4.1         
[10] rCharts_0.4.2        RSQLite_1.0.0        DBI_0.3.1

**Comment by wch** [comment]
This should work on the latest version. Can you post the output of `devtools::session_info()`? Also, please make sure to start a clean R session after installing shinydashboard.

**Comment by happyshows** [comment]
Hi,

I just tried and still see the same error. devtools::session_info() attached.

Session info------------------------------------------------------------------------------------------------------
 setting  value                         
 version  R version 3.1.2 (2014-10-31)  
 system   x86_64, mingw32               
 ui       RStudio (0.98.1091)           
 language (EN)                          
 collate  Chinese (Simplified)_China.936
 tz       America/Chicago               

Packages----------------------------------------------------------------------------------------------------------
 package        * version   date       source                                 
 devtools         1.6.1     2014-10-07 CRAN (R 3.1.1)                         
 digest           0.6.4     2013-12-03 CRAN (R 3.1.1)                         
 htmltools        0.2.6     2014-09-08 CRAN (R 3.1.1)                         
 httpuv           1.3.2     2014-10-23 CRAN (R 3.1.2)                         
 httr             0.5       2014-09-02 CRAN (R 3.1.1)                         
 mime             0.2       2014-09-26 CRAN (R 3.1.1)                         
 R6               2.0       2014-08-19 CRAN (R 3.1.1)                         
 Rcpp             0.11.3    2014-09-29 CRAN (R 3.1.1)                         
 RCurl            1.95.4.3  2014-07-29 CRAN (R 3.1.1)                         
 RJSONIO          1.3.0     2014-07-28 CRAN (R 3.1.1)                         
 rstudio          0.98.1091 2015-02-05 local                                  
 rstudioapi       0.2       2014-12-31 CRAN (R 3.1.2)                         
 shiny          * 0.11      2015-01-17 CRAN (R 3.1.2)                         
 shinydashboard * 0.2.2     2015-02-24 Github (rstudio/shinydashboard@06c7e73)
 stringr          0.6.2     2012-12-06 CRAN (R 3.1.1)                         
 xtable           1.7.4     2014-09-12 CRAN (R 3.1.1)

**Comment by wch** [comment]
Oh, I think I see the problem. I believe you need to upgrade shiny to 0.11.1, with `install.packages('shiny')`.

I've also just updated shinydashboard's required shiny version to 0.11.1

**Comment by happyshows** [comment]
Confirmed, upgrading shiny package solves this issue.
