### ISSUE TITLE
New and Free Bootstrap Admin Template 2016

### ISSUE THREAD

**Issue by JianWang2016** [rstudio/shinydashboard#143]
There is a new [Admin](https://colorlib.com/polygon/gentelella/index.html) template with clean and flat design.  Could someone kindly take a look and see if it is possible to use this one in shiny dashboard?

**Comment by bborgesr** [comment]
Unfortunately, shinydashboard was built on top of the [adminLTE project](https://github.com/almasaeed2010/AdminLTE), not [the project this newer one](https://github.com/puikinsh/gentelella) is built on. I'm afraid you'll have to customize shinydashboard using css if you want a similar look...
