### ISSUE TITLE
Hide/show dashboard sidebar on mouse hover 

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [rstudio/shinydashboard#144]
Hi there,

I'd like to know if someone has already implemented this feature on this shinydashboard similar to 
`safari` website when you read books. If not , any guides on how to do it?

**Comment by bborgesr** [comment]
Sorry for the very late reply. It would help if you could share a link that explains or demoes the desired effect. In any case, we're not likely to implement this type of functionality in shinydashboard itself. This looks like something that should be done in your app with JS and/or CSS. If you disagree or would like to discuss this further, let me know and I can reopen the issue.
