### ISSUE TITLE
sidebarUserPanel() background will be override by leafletfix.css:8 when use leaflet package together with shinydashboard.

### ISSUE THREAD

**Issue by gyang274** [rstudio/shinydashboard#146]
I find that `leafletfix.css:8` in `leaflet` overrides `shinydashboard` css, and makes the `sidebarUserPanel()` having grey box prominent from the black background. In my opinion, this is unconformable aesthetically. I fixed it by adding `style="background-color:transparent;"` in `div(class = "user-panel", ..., div(class = "pull-left info", ...))` in `sidebarUserPanel()` source code.

An example of the issue:

```
## app.R ##
library(shiny)
library(shinydashboard)

library(leaflet)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(
    sidebarUserPanel(name = "Ex Machina", subtitle = "Hello World!")
  ),
  dashboardBody(
    leaflet() %>% addTiles()
  )
)

server <- function(input, output) { }

shinyApp(ui, server)
```

![sidebaruserpanel_01](https://cloud.githubusercontent.com/assets/13155537/16698780/0af5f820-451e-11e6-925d-303e505f9148.png)
![sidebaruserpanel_02](https://cloud.githubusercontent.com/assets/13155537/16698781/0af6dea2-451e-11e6-9df2-69e82dd42674.png)
![sidebaruserpanel_03](https://cloud.githubusercontent.com/assets/13155537/16698782/0af9552e-451e-11e6-9631-c56b502f0561.png)

Thank you!

**Comment by Kbrother1024** [comment]
Thanks! I'm having the same issue with you! Thanks for sharing

**Comment by ShinyFabio** [comment]
Hi I'm facing the same problem. How can I add that div options inside my code?

**Comment by IguanMat** [comment]
> Hi I'm facing the same problem. How can I add that div options inside my code?

I would like to know the same thing
