### ISSUE TITLE
tabItem does not Allow the same content

### ISSUE THREAD

**Issue by happyshows** [rstudio/shinydashboard#15]
The following code will break the whole dashboard, making it stale. I remember shiny tabsetPanel do allow such behaviour. The reason I'm asking is to utilize shiny-particals framework for better code management.
https://github.com/jcheng5/shiny-partials/blob/master/server.R

                tabItems(
                  tabItem("tab_designFlow",uiOutput("ui_container")),
                  tabItem("tab_uploadData",uiOutput("ui_container"))
                )

is there any chance it will be fixed soon?

**Comment by wch** [comment]
You can't use two `uiOutput`s with the same ID -- this creates invalid HTML, which is probably why the app isn't working.
