### ISSUE TITLE
Tabs should support bookmarking

### ISSUE THREAD

**Issue by wch** [rstudio/shinydashboard#154]

**Comment by wch** [comment]
Duplicate of #152.

**Comment by kshitij0987** [comment]
Restoring a menuSubItem tab from bookmark doesn't work if the menuSubItem is 2nd level nested inside two menuItems. For example a restoring a bookmark on "subitem" tab doesn't work in the following case: 
`menuItem('menuitem1',
                                    menuItem("nested_menuitem1",
                                             menuSubItem("subitem1", tabName = "subitem")))`
An extension to #157 #152
