### ISSUE TITLE
How to generate menuItem & menuSubItem dynamically

### ISSUE THREAD

**Issue by teramonagi** [rstudio/shinydashboard#16]
Dear developers;

I really I appreciate your efforts to maintain this nice library.

I have a one question to use this. I tried to make menuItem & menuSubItem dynamically like you explained for DropdownMenu in the following document:

- http://rstudio.github.io/shinydashboard/structure.html#dynamic-content

There are special functions to generate Dropdown dynamically :  
- renderDropdownMenu
- dropdownMenuOutput 

I already read the source code related to this topic and I understood that if I want to do the same thing for menuItem, I have to...

1. Make special tag(e.g. shinydashboard-menu-output) for its rendering
2. To render correctly, I need to modified shinydashboard.js 

Is my understanding correct?

**Comment by wch** [comment]
Thanks for the idea. I've added some functions to make this possible, in 9f88997 and 4d2a719. See http://rstudio.github.io/shinydashboard/structure.html#dynamic-content-1 for examples.

**Comment by teramonagi** [comment]
Looks Perfect To Me :) :+1:
