### ISSUE TITLE
Warning: Error in exists: invalid first argument

### ISSUE THREAD

**Issue by SenseMaster** [rstudio/shinydashboard#160]
Bug appears when I running my app on AWS with:

- shiny+rstudio
- https tuned by the instruction from: https://www.r-bloggers.com/installing-rstudio-shiny-server-on-aws/
- ssl tuned by the instruction from: https://www.r-bloggers.com/shiny-https-securing-shiny-open-source-with-ssl/
- password on shiny server tuned by instruction: https://www.r-bloggers.com/password-protect-shiny-apps/

# SESSIONINFO:
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinydashboard_0.5.2 shinyjs_0.7          shiny_0.14          

loaded via a namespace (and not attached):
 [1] R6_2.1.3        htmltools_0.3.5 tools_3.3.1     Rcpp_0.12.7     jsonlite_1.1    digest_0.6.10   xtable_1.8-2    httpuv_1.3.3    miniUI_0.1.1   
[10] mime_0.5       

# **How to reproduce:**
1. Create ui.R with this content (https://rstudio.github.io/shinydashboard/structure.html#dynamic-content-1):

library(shiny)
library(shinydashboard)
shinyUI(dashboardPage(
   dashboardHeader(title = "Dynamic sidebar"),
   dashboardSidebar(
     sidebarMenuOutput("menu")
   ),
   dashboardBody()
 )
)

2. Create server.R with this content (https://rstudio.github.io/shinydashboard/structure.html#dynamic-content-1):

library(shiny)
library(shinyjs)
library(shinydashboard)
shinyServer(function(input, output, session) {
   output$menu = renderMenu({
     sidebarMenu(
       menuItem("Menu item", icon = icon("calendar"))
       )
     })
 }
)

3. Create new script with runApp() function with a correct way to the app.

4. Run the app from the rstudio-server environment.
(permissions to project files 777)

See the error:

Listening on http://127.0.0.1:3339
Warning: Error in exists: invalid first argument
Stack trace (innermost first):
    84: exists
    83: self$exists
    82: oldInputs$available
    81: shiny::restoreInput
    80: sidebarMenu
    79: renderMenu [/home/rstudio/test/server.R#7]
    78: func
    77: origRenderFunc
    76: output$menu
     1: runApp

If I run app directly from server ( \srv\test ) then
![image](https://cloud.githubusercontent.com/assets/15361305/18665181/a0a19cfe-7f2e-11e6-9277-9136a89c8df0.png)
![image](https://cloud.githubusercontent.com/assets/15361305/18665563/8bf0e34e-7f30-11e6-85a7-31f6f24d3b62.png)

**Comment by wch** [comment]
Sorry about that. I've just fixed it. You can install the development version with:

```R
if (!requireNamespace('devtools'))
  install.packages('devtools')
devtools::install_github('rstudio/shinydashboard')
```

I'll try to release an updated version of shinydashboard to CRAN shortly.

**Comment by wch** [comment]
This is related to rstudio/shiny#1382.

**Comment by wch** [comment]
The new version is on CRAN now, though it will take some time for it to propagate to mirrors, and for various binary packages to be built.

**Comment by SenseMaster** [comment]
Thank you!
