### ISSUE TITLE
Box doesn't resize with fixed Plotly graph height inside of it

### ISSUE THREAD

**Issue by slavakx** [rstudio/shinydashboard#164]
Hi, 

I am sure there is a solution to this problem. 
I've put a plotly graph inside the box

box(collapsible = TRUE, title = "Title", status = "primary", solidHeader = TRUE, width = NULL, collapsed = TRUE, plotlyOutput("plotlygraph"))

This works fine when plotly graph has autosize = TRUE - the graph is within the boundaries of the box 

However I want to fix the size of the plotly graph like this: layout(autosize = FALSE, height = 500)

I tried two solutions which do not work for me:
1. Leave height = NULL for the box because the doc says: By default the height scales automatically with the content - this doesn't work and the plotly graph is out of boundaries of the box
2. Provide height = XXX for the box but this leaves the box "non collapsed"

Hope to get your help

**Comment by cinkie** [comment]
Put the plotly graph within the column. This should work.
```
box(
collapsible = TRUE, title = "Title", status = "primary", solidHeader = TRUE, width = NULL, collapsed = TRUE, 
column(width = 12, plotlyOutput("plotlygraph"))
)
```

**Comment by bborgesr** [comment]
I'm not sure @cinkie's suggestion is enough. But it seems like just setting `height = "500px"` as an argument to `plotlyOutput()` should be enough:

```r
library(shiny)
library(shinydashboard)
library(plotly)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    box(
      collapsible = TRUE, title = "Title", status = "primary", solidHeader = TRUE, width = NULL, collapsed = TRUE, 
      plotlyOutput("plotlygraph", height = "500px")
    )
  )
)

server <- function(input, output, session) {
  output$plotlygraph <- renderPlotly({
    plot_ly(mtcars, x = ~mpg, y = ~wt) %>%  layout(autosize = FALSE, height = 500)
  })
}

shinyApp(ui = ui, server = server) 
```

So, I'll close this for now. If I misread your question, let me know and we can reopen.
