### ISSUE TITLE
Include jQuery results in broken App

### ISSUE THREAD

**Issue by Stophface** [rstudio/shinydashboard#166]
I try to include jQuery into Shiny Dashboard.
`tags$script(src = "https://code.jquery.com/jquery-3.1.1.min.js")`

That breaks the app completey. Buttons are not clickable anymore, the whole layout gets messed up and so forth. Are you not allowed to include jQuery in Shiny Dashboard?
Note: With the "normal" Shiny App it works perfectly fine!

**Comment by wch** [comment]
Shiny already includes a different version of jQuery. Adding another, different version of jQuery is likely leading to a conflict. The fact that it works in some cases isn't a guarantee that it will work in all cases.

**Comment by Stophface** [comment]
@wch What version of jQuery is it using? Because some of the jQuery functions I use work, others don't. Is that written somewhere in the docs?

**Comment by wch** [comment]
It depends on which version of Shiny you're using. The easy way to check is to "View page source" in your browser.
