### ISSUE TITLE
Feature request: input inside menuItem

### ISSUE THREAD

**Issue by adiell** [rstudio/shinydashboard#167]
Hi, 
It would be great if input can be nested inside menuItem. For example:

```r
ui <- dashboardPage(
  dashboardHeader(title = "Example"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Item1", tabName = "tab1",
               textInput("input1", "Enter text")),
      menuItem("Item2", tabName = "tab2",
               numericInput("input2", "Enter a number", 0))
    )
    ),
  dashboardBody(
    tabItems(
      tabItem("tab1", textOutput("text1")),
      tabItem("tab2", textOutput("text2"))
    )
  )
)
server <- shinyServer(function(input, output) {
    output$text1 <- renderText({"Text1"})
    output$text2 <- renderText({"Text2"})
})

shinyApp(ui = ui, server = server)
```

The sidebar menu is actually displayed correctly but the content of the body isn't....

Thanks,
Adiel

**Comment by bborgesr** [comment]
Sorry for the very late reply.

You've run into a limitation (or, better said, a peculiarity) of `menuItem()`s in AdminLTE, that has also been adopted by shinydashboard. You can have two types of `menuItem()`s: childless ones and "childfull" ones. In your case, you have children in both `menuItem()`s (i.e. there's stuff that can either be expanded or collapsed). Now, if a particular `menuItem()` has children, that `menuItem()` cannot be used for navigation (so while you can pass it a `tabName` argument, this is basically ignored by shinydashboard). 

This may seem a limitation, like I said. But I think it actually makes sense. In your app above, for example, you want a click on either of the `menuItem()`s to do two things simultaneously:

1. Navigate to the appropriate `tabItem()`;
2. Display the `menuItem()`'s children.

I'd argue that it's best to force users to think about these as separate events and not allow them (certainly not by default) to be smashed together.

If this "smashed" behavior is super important for you, there will soon be a way to accomplish this behavior in `shinydashboard` soon (just finishing these changes in a separate branch right now). If you want a sneak peak, you can install that version of shinydashboard:

```r
devtools::install_github("rstudio/shinydashboard@barbara/changes")
```

and run the following example:

```r
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Item1", expandedName = "tab1",
        textInput("input1", "Enter text")),
      menuItem("Item2", expandedName = "tab2",
        numericInput("input2", "Enter a number", 0))
    )
  ),
  dashboardBody(uiOutput("body"))
)

server <- function(input, output, session) {
  output$body <- renderUI({
    if (is.null(input$sidebarItemExpanded)) {
      "No menuItem is expanded at the moment"
    } else if (input$sidebarItemExpanded == "tab1") {
      textOutput("text1")
    } else if (input$sidebarItemExpanded == "tab2") {
      textOutput("text2")
    }
  })
  
  output$text1 <- renderText({ paste("Your text is", input$input1) })
  output$text2 <- renderText({ paste("Your number is", input$input2) })
}

shinyApp(ui, server)
```

As you can see, this doesn't use the `tabName` argument and it uses the `expandedName` argument instead. It also doesn't use `tabItems()` at all. Instead, it decides what to render in the dashboard body through uiOutput/renderUI. There's quite a bit of new stuff there. You can see a preview of the write-up that will be published on shinydashboard's website once this is released here: https://bborgesr.github.io/shinydashboard/behavior.html

Let me know if you have any questions or comments.

**Comment by tobiasdirksen** [comment]
Using the above example, how do I expand a sidebarItem? `UpdateTabItem` doesn't work here? See https://stackoverflow.com/questions/51023656/problems-with-updatetabitems-in-shinydashboard
