### ISSUE TITLE
jQuery noConflict breaks shinydashboard

### ISSUE THREAD

**Issue by heejongkim** [rstudio/shinydashboard#172]
Hello,

After days of struggling with htmlwidgets to wrap jQuery-based libraries, I finally got it working in a simple shiny scaffold. Unfortunately, as soon as I put that in the shinydashboard based app with $.noConflict(true);, it breaks shinydashboard with the error msg:
Uncaught TypeError: $ is not a function
Is there a recommended way to handle this?
Thanks.

**Comment by wch** [comment]
Can you provide a minimal reproducible example?

**Comment by bborgesr** [comment]
I suspect this is because you're not waiting for the app to be fully loaded. A common way around this for Shiny is to wrap your JS in `$(document).on('shiny:connected', function() { [YOUR JS HERE] });"`, like so:

```r
library(shiny)
library(shinydashboard)

shinyApp(
  ui = dashboardPage(
    dashboardHeader(),
    dashboardSidebar(),
    dashboardBody(
      tags$head(tags$script(HTML(
        "$(document).on('shiny:connected', function() {
          // [your code] 
          $.noConflict(true)
        });"
      )))
    ),
    title = "Dashboard example"
  ),
  server = function(input, output, session) {}
)
```

If this is still giving you problems, let us know and we can reopen the issue.
