### ISSUE TITLE
sidebar width property screws up mobile rendering

### ISSUE THREAD

**Issue by lukewp** [rstudio/shinydashboard#177]
If you set width for a sidebar, when you call the page from mobile, part of the sidebar may never go away, obscuring part of the content like this:
![image](https://cloud.githubusercontent.com/assets/2334033/22091260/3a8f8666-ddc4-11e6-8a8d-45a2d6115385.png)

One solution that gets the dashboard rendering properly on mobile is to remove the sidebar width property from the code.

**Comment by wch** [comment]
Probably related to #127.
