### ISSUE TITLE
Make sure bookmarking works

### ISSUE THREAD

**Issue by wch** [rstudio/shinydashboard#179]
Features to check:

- [x] Selected tab in menuItem and menuSubItem is saved. (May be related to #128.)
- [x] Sidebar menuItem expanded state is saved.

**Comment by bborgesr** [comment]
In addition:
- [ ] Sidebar expanded/collapsed state

So, in summary, we have to add "bookmarkability" for:
- [ ] sidebar expanded/collapsed state
- [ ] menuItems expanded/collapsed state
- [ ] subMenuItem that is selected/active

Possible solutions:
- give inputId, like `tabsetPanel` (gives bookmarkability by default). This would also address #114 (and allow us to close the corresponding PR, #128)
- create new function(s) to be used inside `onBookmark` and `onRestore` (no default bookmarkability)

**Comment by bborgesr** [comment]
Closed in #199
