### ISSUE TITLE
Unable to use "Run App button" in RStudio Version 0.99

### ISSUE THREAD

**Issue by ksmzn** [rstudio/shinydashboard#18]
Hi.
Thanks for making this great package.

My `RStudio` (Version 0.99.331) doesn't  recognize the `Shiny` script with `shinydashboard` and provide a Run App button.

Here is a screenshot.
![2015-03-13 18 46 22](https://cloud.githubusercontent.com/assets/4282797/6636214/48f2df60-c9b1-11e4-897a-f95d6916c9f7.png)

**Comment by jjallaire** [comment]
@wch Is this a fully formed ui.R? (i.e. is there a call to shinyUI still necessary to make it complete?). If it's not fully formed that's why there is no runApp. If it is is fully formed then we need to make a change in RStudio to detect this variation of ui.R.  @jmcphers

**Comment by wch** [comment]
@jjallaire it is a valid ui.R file, but the `ui <-` isn't actually necessary here. As long as the ui.R returns a `bootstrapPage()`, `fluidPage()`, etc., it's a valid ui.R. The `shinyUI` hasn't been necessary since 0.9 or 0.10, I think.

**Comment by jjallaire** [comment]
Okay, I've updated our filter as follows:

https://github.com/rstudio/rstudio/commit/5eef894a336994e0d8afd86c667060f2fe559e55

@jmcphers Does that look okay to you?

**Comment by jmcphers** [comment]
Yes, that looks good. Thanks guys!

**Comment by ksmzn** [comment]
Thank you everyone!
