### ISSUE TITLE
no response when switching between menuSubItems after first clicked actionButton

### ISSUE THREAD

**Issue by earthcli** [rstudio/shinydashboard#180]
By using shiny and shinydashboard package, I have create a group of menuItems and menuSubItems as well as the coresponding tabItems, and there is a conditionalPanel with different input parameters for each menuSubItems, and an actionButton for different analysing and ploting task, now it works before the actionButton is clicked, that is, the conditionalPanel changed when switching between menuSubItems, and it also works well for the first time actionButton is clicked,  it show a plot html as expected, but after the first clicked of actionButton, the conditionalPanel no longer changed as before when switching between menuSubItems, and the sidebar can not be collapsed as before,  it seems that the menuSubItems can not update when clicked by mouse in the ui, 
I think I need something like updateTabItems(session, "tabs", newtab),but it still does not work when an added "observeEvent(input$sidebarmenu,updateTabItems(session, "sidebarmenu", input$sidebarmenu))"
How can I fix it?
but I wonder How it works for the first time actionButton is clicked, while does not work for the second time ?
the programs is so long that, I can only paste a piece of them as follows: the myshinyOutput is a selfdefined function for creating a html with input parameters.

and I have post a question on stackoverflow:
http://stackoverflow.com/questions/42269571/shiny-different-tasks-with-actionbutton-for-each-menusubitems

```
library(shiny)
library(shinyjs)
library(shinydashboard)
library(knitr)
library(markdown)
library(rmarkdown) 
library(ggplot2)

# parinbox #############################
jsboxcollapsecode <- "shinyjs.collapse = function(boxid) {
$('#' + boxid).closest('.box').find('[data-widget=collapse]').click();
}
"
selDateRange=dateRangeInput('dateRange',label='time:',start=Sys.Date()-7,end=Sys.Date()-1) 
selcompyear=textInput("compyear",label="compyear:")
selmetsInput=selectInput(inputId="selmets",label="item:",choices=c("a","b","c"),selected=c("a","b"),multiple=TRUE)
condselcompyear =conditionalPanel("input.sidebarmenu=='subItemOne'||input.sidebarmenu=='subItemFour'",selcompyear)
condselmetsInput=conditionalPanel("input.sidebarmenu=='subItemThree'",selmetsInput)

runButton=actionButton(inputId="runButton",label=strong("run"),width=100)
opendirButton=actionButton(inputId="opendirButton",label=strong("opendir"),width=100)
fluidrunopenButton=fluidRow(column(4,offset=1,runButton),column(width=4,offset=1,opendirButton))

parInbox=box(id="parbox",title="Input parameter",status="primary",solidHeader=TRUE,collapsible=TRUE,collapsed=FALSE,width='auto',
             selDateRange,condselcompyear,condselmetsInput,fluidrunopenButton)
absParInPanel=absolutePanel(id="parinbox",top=80,right=0,width=300,draggable=TRUE,parInbox)                                           

# Sidebar #############################
sidebar <- dashboardSidebar(
  tags$head(
    tags$script(
      HTML(
        "
        $(document).ready(function(){
        // Bind classes to menu items, easiet to fill in manually
        var ids = ['subItemOne','subItemTwo','subItemThree','subItemFour'];
        for(i=0; i<ids.length; i++){
        $('a[data-value='+ids[i]+']').addClass('my_subitem_class');
        }

        // Register click handeler
        $('.my_subitem_class').on('click',function(){
        // Unactive menuSubItems
        $('.my_subitem_class').parent().removeClass('active');
        })
        })
        "
      )
    )
    ),
  width = 290,
  sidebarMenu(id='sidebarmenu',
              menuItem('Menu One', tabName = 'menuOne', icon = icon('line-chart'),
                       menuSubItem('Sub-Item One', tabName = 'subItemOne'),
                       menuSubItem('Sub-Item Two', tabName = 'subItemTwo')),


              menuItem('Menu Two', tabName = 'menuTwo', icon = icon('users'), 
                       menuSubItem('Sub-Item Three', tabName = 'subItemThree'),
                       menuSubItem('Sub-Item Four', tabName = 'subItemFour')))

  # sidebarMenu(
  #   menuItem('Menu Two', tabName = 'menuTwo', icon = icon('users'), 
  #            menuSubItem('Sub-Item Three', tabName = 'subItemThree'),
  #            menuSubItem('Sub-Item Four', tabName = 'subItemFour')))
    )
# Body #############################
body <- dashboardBody(
  useShinyjs(), 
  extendShinyjs(text=jsboxcollapsecode),
  absParInPanel,
  tabItems(
    tabItem(tabName = 'subItemOne',
            h2('Selected Sub-Item One'),uiOutput('subItemOne_html')),

    tabItem(tabName = 'subItemTwo',
            h2('Selected Sub-Item Two'),uiOutput('subItemTwo_html')),

    tabItem(tabName = 'subItemThree',
            h2('Selected Sub-Item Three'),uiOutput('subItemThree_html')),

    tabItem(tabName = 'subItemFour',
            h2('Selected Sub-Item Four'),uiOutput('subItemFour_html'))

  )
)
# UI #############################
ui <- dashboardPage(
  dashboardHeader(title = 'Test', titleWidth = 290),
  sidebar,
  body
)
# Server #############################
server <- function(input, output){

  shinyOutput<- function(input=NULL){
    sidebarmenu=input$sidebarmenu
    start=as.Date(format(input$dateRange[1]))
    end=as.Date(format(input$dateRange[2]))
    time=seq(from=start,to=end+5,by="day")
    gdata=data.frame(x=time,y=sample(1:100,length(time)))
    if(sidebarmenu=='subItemOne'){
      ggsave(ggplot(gdata,aes(x,y))+geom_line(),device="png",filename="tmp.png")
    }else if(sidebarmenu=='subItemTwo'){
      ggsave(ggplot(gdata,aes(x,y))+geom_col(),device="png",filename="tmp.png")
    }else if(sidebarmenu=='subItemThree'){
      ggsave(ggplot(gdata,aes(x,y))+geom_dotplot(),device="png",filename="tmp.png")
    }else if(sidebarmenu=='subItemFour'){
      ggsave(ggplot(gdata,aes(x,y))+geom_col(fill="red"),device="png",filename="tmp.png")
    }
    Rmdfile="tmp.Rmd"
    writeLines(c("---","output: 'html_document'","---","```{r rcode,cache=FALSE}","knitr::include_graphics('tmp.png')","```"),Rmdfile)
    shiny::includeHTML(rmarkdown::render(Rmdfile,clean=FALSE))
  }
  htmlvalues=reactive({
    if(input$runButton==0) return()
    isolate({
      input$runButton
      renderUI({shinyOutput(input)})
    })
  })
  observeEvent(input$runButton,
               {
                 js$collapse("parbox")
                 print(paste("the current selected submenu is",input$sidebarmenu,sep=":"))
                 output[[paste(input$sidebarmenu,"html",sep="_")]]=htmlvalues()
               })
}

shinyApp(ui, server)

# > sessionInfo()
# R version 3.3.2 (2016-10-31)
# Platform: i386-w64-mingw32/i386 (32-bit)
# Running under: Windows 7 (build 7600)
# 
# 
# other attached packages:
#   [1] shinydashboard_0.5.3
# [2] shiny_1.0.0         
# 
# loaded via a namespace (and not attached):
#   [1] R6_2.1.1        htmltools_0.3.5
# [3] tools_3.3.2     Rcpp_0.12.9    
# [5] digest_0.6.8    xtable_1.7-4   
# [7] httpuv_1.3.3    mime_0.3
```

**Comment by bborgesr** [comment]
I'm sorry, I really cannot understand the issue from such a long example. Can you please post a minimal reproducible example?

**Comment by bborgesr** [comment]
Here's a simpler example, that is a little different. Let me know if this works for you:

```r
library(shiny)
library(shinydashboard)
library(rmarkdown) 
library(ggplot2)

ui <- dashboardPage(
  dashboardHeader(title = 'Test'),
  
  # sidebar
  dashboardSidebar(
    sidebarMenu(id='sidebarmenu',
      menuItem('Menu One', tabName = 'menuOne',
        menuSubItem('Sub-Item One', tabName = 'subItemOne'),
        menuSubItem('Sub-Item Two', tabName = 'subItemTwo')
      ),
      menuItem('Menu Two', tabName = 'menuTwo', 
        menuSubItem('Sub-Item Three', tabName = 'subItemThree'),
        menuSubItem('Sub-Item Four', tabName = 'subItemFour')
      )
    )
  ),
  
  # body
  dashboardBody(
    absolutePanel(id = "parinbox", top = 80, right = 0, width = 300,
      box(id = "parbox",
        dateRangeInput('dateRange', 'time:', start = Sys.Date() - 7, end = Sys.Date() - 1),
        conditionalPanel("input.sidebarmenu == 'subItemOne' || input.sidebarmenu == 'subItemFour'",
          textInput("compyear", "compyear:")
        ),
        conditionalPanel("input.sidebarmenu=='subItemThree'",
          selectInput(inputId = "selmets", "item:", c("a","b","c"), c("a","b"), TRUE)
        ),
        fluidRow(column(4, offset = 1, actionButton(inputId = "run", "run")))
      )
    ), 
    
    uiOutput("title"),
    plotOutput("plt")
  )
)


server <- function(input, output, session) {
  output$plt <- renderPlot({
    req(input$run)
    switch (input$sidebarmenu,
      subItemOne = plot(cars),
      subItemTwo = plot(pressure),
      subItemThree = plot(faithful),
      subItemFour = plot(women)
    )
  })
  
  output$title <- renderUI({
    req(input$run)
    h2(paste('Selected', input$sidebarmenu))
  })
}

shinyApp(ui, server)
```

**Comment by earthcli** [comment]
Dear bborgesr, Thanks for your kindly response!
I have found the problem from stackoverflow, it seems that the 'includeHTML' has caused this mistake, may be this is a bug of shinydashboard package.

 if a rmarkdown html is injected directly with shiny::includeHTML, the input$sidebarmenu would not change any more, maybe the injected html would destruct the inner settings of shinydashboard.

I fixed it with htmltools::HTML(markdown::markdownToHTML(knit(Rmdfile,quiet=‌​TRUE))), and it works.

I need to include a html from a rmarkdown, because I have many scripts to generate plots to disk(with well formated fonts and plot size), now I do not want to recode these scripts, so I want to just include theses plots into a html, but theres is still two problem:

1, the markdownToHTML seems not friendly with chinese word in the plot paths, 
2, if I exclude the "base64_images" from the markdown.HTML.options, it does not works any more(I think it may be fast if the local plots is not embed into the html, but it not works, it only works with markdownToHTML generate a html and then includeHTML )

a minimal repeatable code is as below:
please pay attention into the line of: options(markdown.HTML.options=c("use_xhtml","smartypants","base64_images","mathjax","highlight_code")[-3])


`library(shiny)
library(shinyjs)
library(shinydashboard)
library(knitr)
library(markdown)
library(rmarkdown) 
library(ggplot2)
options(markdown.HTML.options=c("use_xhtml","smartypants","base64_images","mathjax","highlight_code")[-3])
# parinbox #############################
jsboxcollapsecode <- "shinyjs.collapse = function(boxid) {
$('#' + boxid).closest('.box').find('[data-widget=collapse]').click();
}
"
selDateRange=dateRangeInput('dateRange',label='time:',start=Sys.Date()-7,end=Sys.Date()-1) 
selcompyear=textInput("compyear",label="compyear:")
selmetsInput=selectInput(inputId="selmets",label="item:",choices=letters,selected=c("a","b"),multiple=TRUE)
condselcompyear =conditionalPanel("input.sidebarmenu=='subItemOne'||input.sidebarmenu=='subItemFour'",selcompyear)
condselmetsInput=conditionalPanel("input.sidebarmenu=='subItemThree'",selmetsInput)

runButton=actionButton(inputId="runButton",label=strong("run"),width=100)
opendirButton=actionButton(inputId="opendirButton",label=strong("opendir"),width=100)
fluidrunopenButton=fluidRow(column(4,offset=1,runButton),column(width=4,offset=1,opendirButton))

parInbox=box(id="parbox",title="Input parameter",status="primary",solidHeader=TRUE,collapsible=TRUE,collapsed=FALSE,width='auto',
             div(style='max-height: 85vh; overflow-x: hidden; overflow-y: auto;',
             selDateRange,condselcompyear,condselmetsInput,fluidrunopenButton))
absParInPanel=absolutePanel(id="parinbox",top=80,right=0,width=300,draggable=TRUE,parInbox)                                           

# Sidebar #############################
sidebar <- dashboardSidebar(
  width = 290,
  sidebarMenu(id='sidebarmenu',
              menuItem('Menu One', tabName = 'menuOne', icon = icon('line-chart'),
                       menuSubItem('Sub-Item One', tabName = 'subItemOne'),
                       menuSubItem('Sub-Item Two', tabName = 'subItemTwo')),
              menuItem('Menu Two', tabName = 'menuTwo', icon = icon('users'), 
                       menuSubItem('Sub-Item Three', tabName = 'subItemThree'),
                       menuSubItem('Sub-Item Four', tabName = 'subItemFour')))

    )
# Body #############################
body <- dashboardBody(
  useShinyjs(), 
  extendShinyjs(text=jsboxcollapsecode),
  absParInPanel,
  tabItems(
    tabItem(tabName = 'subItemOne',
            h2('Selected Sub-Item One'),uiOutput('subItemOne_html')),
    
    tabItem(tabName = 'subItemTwo',
            h2('Selected Sub-Item Two'),uiOutput('subItemTwo_html')),
    
    tabItem(tabName = 'subItemThree',
            h2('Selected Sub-Item Three'),uiOutput('subItemThree_html')),
    
    tabItem(tabName = 'subItemFour',
            h2('Selected Sub-Item Four'),uiOutput('subItemFour_html'))
    
  )
)
# UI #############################
ui <- dashboardPage(
  dashboardHeader(title = 'Test', titleWidth = 290),
  sidebar,
  body
)
# Server #############################
server <- function(input, output){
  
  shinyOutput<- function(input=NULL){
    sidebarmenu=input$sidebarmenu
    imagename="tmp.png"
    start=as.Date(format(input$dateRange[1]))
    end=as.Date(format(input$dateRange[2]))
    time=seq(from=start,to=end+5,by="day")
    gdata=data.frame(x=time,y=sample(1:100,length(time)))
    if(sidebarmenu=='subItemOne'){
      ggsave(ggplot(gdata,aes(x,y))+geom_line(),device="png",filename=imagename)
    }else if(sidebarmenu=='subItemTwo'){
      ggsave(ggplot(gdata,aes(x,y))+geom_col(),device="png",filename=imagename)
    }else if(sidebarmenu=='subItemThree'){
      ggsave(ggplot(gdata,aes(x,y))+geom_dotplot(),device="png",filename=imagename)
    }else if(sidebarmenu=='subItemFour'){
      ggsave(ggplot(gdata,aes(x,y))+geom_col(fill="red"),device="png",filename=imagename)
    }
    Rmdfile="tmp.Rmd"
    writeLines(c("---","output: 'html_document'","---","```{r rcode,cache=FALSE}","knitr::include_graphics('tmp.png')","```"),Rmdfile)
    #shiny::includeHTML(rmarkdown::render(Rmdfile,clean=FALSE))
    htmltools::HTML(markdown::markdownToHTML(knit(Rmdfile,quiet=TRUE),fragment.only=FALSE))
  }
  
  htmlvalues <- reactiveValues() # use a reactiveValue to store rendered html for each subItem
  
  observeEvent(input$runButton, {
    htmlvalues[[input$sidebarmenu]] <- shinyOutput(input)
  })
  
  for(item in c('subItemOne','subItemTwo','subItemThree','subItemFour')) {
    local({ ## use local to ensure the renderUI expression get correct item
      current_item <- item
      output[[paste(current_item,"html",sep="_")]] <- renderUI({
        htmlvalues[[current_item]]
      })
    })
  }
  
}

shinyApp(ui, server)`
