### ISSUE TITLE
sidebarMenu id doesn't work if generated from server

### ISSUE THREAD

**Issue by carlganz** [rstudio/shinydashboard#183]
```{R}
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
 dashboardHeader(),
 dashboardSidebar(
 sidebarMenuOutput("one"),
 sidebarMenu(id = "bar2",
 lapply(1:3, function(i) {
 x <- stringi::stri_rand_strings(1, 5)
 menuItem(x, tabName = x)
 }))

),
 dashboardBody(
 uiOutput("test")
 ),
 title = "Dashboard example"
)

server <- function(input, output, session) {

output$one <- renderMenu({

sidebarMenu(id = "bar",
 lapply(1:3, function(i) {
 x <- stringi::stri_rand_strings(1, 5)
 menuItem(x, tabName = x)
 }))
 })

observe({
 print(input$bar)
 print(input$bar2)
 })

}

shinyApp(ui, server)
```

There are two sidebar menus one created in the UI and one on the Server. The id works for one but not the other. `input$bar` is always NULL

**Comment by bborgesr** [comment]
I don't think AdminLTE supports multiple sidebar menus, and `shinydashboard` certainly doesn't right now. Can you explain why you'd need this?

The dynamic menu works perfectly fine as long as it's the only one present:

```r
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(
    sidebarMenuOutput("menu")
  ),
  dashboardBody()
)

server <- function(input, output, session) {
  output$menu <- renderMenu({
    sidebarMenu(id = "sidebar",
      menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
      menuItem("Widgets", tabName = "widgets", icon = icon("th"))
    )
  })
  
  observe(print(input$sidebar))
}

shinyApp(ui, server)
```

**Comment by bborgesr** [comment]
Closing this issue now, since the title is misleading. If you want to open a new issue for allowing multiple sidebar menus in the same app, feel free. If you just want to discuss the possibility, we can continue doing so through here.

**Comment by carlganz** [comment]
Sorry about the title. I clearly misidentified the problem.

This is from a few months back so I honestly don't remember exactly what my use case was. I think it was essentially a nested menu system, i.e. the choice in the first menu dictates the options in the second menu, which then dictates the content of the dashboard. 

There are other ways of doing essentially the same thing so it's not a big deal. 

Kind Regards,
Carl

**Comment by bborgesr** [comment]
> This is from a few months back so I honestly don't remember exactly what my use case was. I think it was essentially a nested menu system, i.e. the choice in the first menu dictates the options in the second menu, which then dictates the content of the dashboard.

Yeah, for that case, I'd recommend that you make the entire sidebar menu dynamic, so you can use logic in the server that renders and re-renders it if necessary.

If this comes up again, and you find that this approach is not enough, let me know.

(no worries about the title! and thanks for being super responsive, unlike us ;) )
