### ISSUE TITLE
renderMenu function for shinydashboard

### ISSUE THREAD

**Issue by taschmitt** [rstudio/shinydashboard#19]
Does the ```renderMenu``` function still exist for shinydashboard? We can't locate it.

**Comment by wch** [comment]
Yes, it's here:
https://github.com/rstudio/shinydashboard/blob/2d1e5f12cf1c3dfaa2aba49888902a2cfec6460b/R/menuOutput.R#L144

You need to install the latest version from Github.

**Comment by taschmitt** [comment]
Great, thanks Winston! Not sure how we missed that . . . .
