### ISSUE TITLE
Is it possible to bookmark in multi page apps

### ISSUE THREAD

**Issue by pssguy** [rstudio/shinydashboard#192]
This may be one of the issues you are currently looking at but, if not,
I have a complex site with one page bookmarked

![bookmarking](https://cloud.githubusercontent.com/assets/2775918/23472105/a51a1b10-fe60-11e6-8d8f-6695c6403472.PNG)

This is the bookmarked url
https://mytinyshinys.shinyapps.io/premierLeague/?_inputs_&boxButton=0&bp_Country=%22England%22&bp_fullScale=%22No%22&bp_Teams=%22All%20Teams%22&goalA=20&goalsSinceCat=%22Goals%20For%22&goalsSinceCount=5&managerGames=27&method=%22Method%22&pcPlGoals=50&pcPlGoalsCat=%22Long%20Range%22&player_tc=%22AGUEROS%22&result=%22Win%22&sbMenu=%22m_ppg%22&seasons=%22Single%22&seqPlVenue=%22All%22&seqVenue=%22All%22&spanA=10&spanVenue=%22All%22&sp_pcFullGames=50&sp_pcFullGamsTeams=%22All%20Teams%22&st_boxGames=25&st_boxPositions=%5B1%2C20%5D&teamA=%22Everton%22&team_cpc=%22Tottenham%20H%22&teamD=%22West%20Ham%20U%22&teamE=%22All%20Teams%22&team_fp=%22Leicester%20C%22&tmGoals=%22For%22&twoTeams=%5B%22Chelsea%22%2C%22Tottenham%20H%22%5D&twoTeamsApp=%22Appeared%22&withClub=%22All%22&yronyrCat=%22Points%22&yronyrRound=25&yronyrTeam=%5B%22Arsenal%22%2C%22Chelsea%22%2C%22Liverpool%22%2C%22Man.%20Utd.%22%5D

If I enter this in a browser, I get sent to the front page rather than the menu I am after. If I switch to the specific menu subitem Managers > Avpoints per game, I seem to get varying outputs. However what I reall want  is the output to immediately reflect what is in the image
tx

**Comment by bborgesr** [comment]
You're right, this is something I'm currently looking at. We should have a solution for you soon. I'll keep you posted :)

**Comment by pssguy** [comment]
Excellent

**Comment by bborgesr** [comment]
Can you give the source code for that app, or then try it with a new fix branch and tell me if fixes your issue?

Here's the code to install the new branch version of shinydashboard:

```r
devtools::install_github("rstudio/shinydashboard@barbara/bookmark")
```

**Comment by pssguy** [comment]
Thanks
I tried the updated package(0.5.3.9000) and it has no impact locally either 'url' or 'server' style
i.e entering the bookmarked url still transfers to the front page. Once you get to correct tab the right output gets shown, as before

It's a pretty complex [site ](https://mytinyshinys.shinyapps.io/premierLeague/) so sending you all code is unlikely to help  but you can see what I mean if you try it

Have you tried a toy example with different tabItems and found that it performs correctly? If so, I will try and create an extremely pared down version of my site and retest

**Comment by bborgesr** [comment]
Yes, I'd just like to try it, I won't try to use it in any other away. As you guessed, I have tried it on a small app and it works fine, and I wanted to make sure that it also works on a complex, real-world app. If you're okay sending me a github repo with the app, I'll try it myself (sometimes people can't share their code, due to proprietary reasons, and that's fine too).

Now, from your answer, though, it seems like you updated the package to the master branch, not to the particular branch that has this fix (we haven't merged it to master yet, because it's not completely polished yet, but it should be functional). I.e. you probably did:

```r
devtools::install_github("rstudio/shinydashboard")
```

instead of:

```r
devtools::install_github("rstudio/shinydashboard@barbara/bookmark")
```

**Comment by pssguy** [comment]
No I did your version copied from your earlier post. 
It did show as Built: R 3.3.2; ; 2017-03-07 03:57:57 UTC; windows in description so not sure if you version is older and that hass impact. probably not it  Also tried with force=TRUE. Restarted R

Retried this morning

I'm a bit reticent to github it all as there are lots of datasets that are confidential. I'll have another look later today

**Comment by bborgesr** [comment]
If you can get me an example without any confidential parts, that'd be great (you can also email me if you prefer, to keep it more private). Otherwise, no worries. 

The example app that works fine is this one:

```r
library(shinydashboard)
library(shiny)

ui <- function(request) {
  sidebar <- dashboardSidebar(
    sidebarMenu(id = "sidebarmenu",
      menuItem("Dashboard", tabName = "dashboard",
        menuSubItem("Subitem 1", "subitem21"),
        menuSubItem("Subitem 2", "subitem22")
      ),
      menuItem("Subitems", tabName = "subitems",
        menuSubItem("Subitem 1", "subitem1"),
        menuSubItem("Subitem 2", "subitem2")
      ),
      menuItem("Widgets", tabName = "widgets")
    )
  )
  dashboardPage(
    dashboardHeader(title = "Simple tabs"),
    sidebar,
    dashboardBody(
      uiOutput('txt'),
      bookmarkButton()
    )
  )
}
server <- function(input, output) {
  output$txt <- renderUI({
    HTML(paste("The selected tab/subtab is", tags$h3(input$sidebarmenu)))
  })
}

enableBookmarking("url")
shinyApp(ui, server)
```

**Comment by bborgesr** [comment]
Oops, sorry, I forgot to include an important detail: you need to give an id to your `sidebarMenu`. Hopefully, that fixes it!

**Comment by pssguy** [comment]
Thnaks
Your example above works as is but as soon as I start loading data files I get issues either first or second time entering bookmark

TBH  my code is a couple of years old(and includes a global.R) and I'm having trouble incorporating it into your example above
Have you tried more complexity via
a) putting different out put in tabitems rather than dashboard body
b) More than one bookmark button
c) loading data
d) using that data to 
    i) create selectInputs
   ii) produce outputs e.g plots via reactives (probably in separate file sourced from server

I do all that + use reactive values but have spent fruitless couple of hours and will have to leave for now

**Comment by bborgesr** [comment]
I made a few more changes and tested it with a more complex app, per your suggestion. I also want to point out that you cannot save uploaded data (using `fileInput`) via URL bookmarking (only save-to-server bookmarking), so that won't work here (or in any Shiny app)... Everything else seems to work though... So if you're still experiencing issues, I'm at a loss for what that could be...

<details>
<summary>Complex app code (hidden for readability)</summary>

```r
library(shinydashboard)
library(shiny)
library(threejs)

ui <- function(request) {
  dashboardPage(
    dashboardHeader(title = "Testing sidebar bookmarkability"),
    dashboardSidebar(
      uiOutput("sidebarControls"),
      sidebarMenu(id = "smenu",
        menuItem("Frontpage", tabName = "front"),
        menuItem("Models",
          menuSubItem("Linear model", "models1"),
          menuSubItem("Logistic regression", "models2")
        ),
        menuItem("Plots",
          helpText("This is help text"),
          menuSubItem("Scatterplot", "plots1"),
          menuSubItem("3D graph", "plots2")
        ),
        menuItem("Tables", tabName = "tables")
      ),
      fileInput("data", "Load data")
    ),
    dashboardBody(
      tabItems(
        tabItem("front",
          h3("Click through the different tabs to see different content"),
          bookmarkButton(id = "bookmark1")
        ),
        tabItem("models1",
          h3("Here's a linear model"),
          verbatimTextOutput("models1"),
          bookmarkButton(id = "bookmark2")
        ),
        tabItem("models2",
          h3("Here's a logistic regression"),
          verbatimTextOutput("models2"),
          bookmarkButton(id = "bookmark3")
        ),
        tabItem("plots1",
          h3("Here's a 2D plot"),
          plotOutput("plots1"),
          bookmarkButton(id = "bookmark4")
        ),
        tabItem("plots2",
          h3("Here's a 3D plot"),
          scatterplotThreeOutput('plots2'),
          bookmarkButton(id = "bookmark5")
        ),
        tabItem("tables",
          h3("Here's a table"),
          tableOutput("tbl"),
          bookmarkButton(id = "bookmark6")
        )
      )
    )
  )
}
server <- function(input, output, session) {

  data <- reactive({
    if (!is.null(input$data)) {
      read.csv(input$data$datapath)
    }
    else {
      mtcars
    }
  })

  output$sidebarControls <- renderUI({
     if (input$smenu %in% c("models1", "models2", "plots1")) {
       tagList(
         selectInput("xaxis", "X axis", names(data()), selected = input$xaxis),
         selectInput("yaxis", "Y axis", names(data()), selected = input$yaxis)
       )
     } else if (input$smenu == "plots2") {
       tagList(
         selectInput("xaxis", "X axis", names(data()), selected = input$xaxis),
         selectInput("yaxis", "Y axis", names(data()), selected = input$yaxis),
         selectInput("zaxis", "Z axis", names(data()), selected = input$zaxis)
       )
     }
  })

  formula <- reactive({
    req(input$yaxis, input$xaxis)
    as.formula(paste(input$yaxis, input$xaxis, sep = " ~ "))
  })

  output$models1 <- renderPrint({
    summary(glm(formula(), data = data()), family = "linear")
  })

  output$models2 <- renderPrint({
    summary(glm(formula(), data = data()), family = "binomial")
  })

  output$plots1 <- renderPlot({
    plot(formula(), data = data())
  })

  output$plots2 <- renderScatterplotThree({
    x <- data()[[input$xaxis]]
    y <- data()[[input$yaxis]]
    z <- data()[[input$zaxis]]
    scatterplot3js(x, y, z)
  })

  output$tbl <- renderTable({
    data()
  })


  bookmarkBtns <- paste0("bookmark", 1:6)
  setBookmarkExclude(bookmarkBtns)
  lapply(as.list(bookmarkBtns), function(btn) {
    observeEvent(input[[btn]], {
      session$doBookmark()
    })
  })

  # observe({
  #   # Trigger this observer every time an input changes
  #   reactiveValuesToList(input)
  #   session$doBookmark()
  # })
  # onBookmarked(function(url) {
  #   updateQueryString(url)
  # })

}

enableBookmarking("url")
shinyApp(ui, server)
```

</details>

**Comment by bborgesr** [comment]
The changes referenced here are now on master and we expect the sidebar to be bookmarkable without any issue. Our [new website section](https://rstudio.github.io/shinydashboard/behavior.html) talks a bit more about the details. Hopefully this works for you. If you still have issues, do you think you could boil it down to a minimal repro and start a new issue? Thanks for the discussion!

**Comment by ddelarosa70** [comment]
Hi. I have problems bookmarking the sidebarMenu state on my app, 
Can you redo the example you have with a two separate files? 
my sidebarMenu has and ID but still does not reloads with the specified value

**Comment by 1beb** [comment]
This page: https://shiny.rstudio.com/articles/advanced-bookmarking.html should really be updated with your note about the sideBarMenu(s) having a unique ID.

**Comment by vinayprakashanalytics808** [comment]
Hi all, Glad connecting you all.

Even I am facing the same difficulty. Not able bookmark reactive tabs state. Any help would be appreciated

The below application is updating the url based on row selected in the DT table and the selected tab. But what happens is, when the user copy paste the url in another tab, it is not opening the specific tab, instead it is opening the default page (url : http://127.0.0.1:XXXX/?tabs=tabs3).

I mean reactive tabs are not working.

Please follow these steps for the reference

Click on any row(say 3) on DT table(Summary tab)
An new tab3 opens (that is fine) which prints 3
Copy the url now (tab3 url)
Paste this url to another tab (Now it returns to Summary tab only and not tab3).
Am I doing something wrong here?

````
library(shiny)
library(DT)

ui <- function(request) {
  shinyUI(navbarPage(
    "Title", id = "inTabset", selected = "Summary",
    tabsetPanel(id = "tabs",
                # tabPanel(
                #   "Readme",tags$head(tags$link(rel = "stylesheet", type="text/css", href="style.css"))
                # ),
                tabPanel(
                  "Summary",
                  dataTableOutput("tab")))
  )
  )
}

server <- function(input, output, session) {
  # Make sure you only bookmark the tabsetPanel
  setBookmarkExclude(isolate(names(input)[names(input) != "tabs"]))
  
  # Every time the tab changes, store the app state as URL bookmark
  observeEvent(input$tabs, {
    session$doBookmark()
  })
  
  # Set callback that stores the app state in the URL
  onBookmarked(function(url) {
    updateQueryString(paste0("?tabs=", input$tabs), mode = "replace")
  })
  # Set callback to restore the app state from the URL
  onRestore(function(state) {
    updateTabsetPanel(inputId = "tabs", selected = getQueryString()[["tabs"]])
  })
  
  output$tab <- renderDataTable({
    datatable(iris,selection = 'single')
  })
  
  observeEvent(input$tab_rows_selected, {
    insertTab(inputId = "tabs",
              tabPanel(paste0("tabs",input$tab_rows_selected), "This a dynamically-added tab",htmlOutput("sd")),
              target = "Summary",select = TRUE
              
    )
  })
  
  output$sd <- renderUI({
    as.character(input$tab_rows_selected)
  })
  
  
}


enableBookmarking("url")
shinyApp(ui, server)
````

**Comment by vinayprakashanalytics808** [comment]
> This may be one of the issues you are currently looking at but, if not, I have a complex site with one page bookmarked
> 
> ![bookmarking](https://cloud.githubusercontent.com/assets/2775918/23472105/a51a1b10-fe60-11e6-8d8f-6695c6403472.PNG)
> 
> This is the bookmarked url https://mytinyshinys.shinyapps.io/premierLeague/?_inputs_&boxButton=0&bp_Country=%22England%22&bp_fullScale=%22No%22&bp_Teams=%22All%20Teams%22&goalA=20&goalsSinceCat=%22Goals%20For%22&goalsSinceCount=5&managerGames=27&method=%22Method%22&pcPlGoals=50&pcPlGoalsCat=%22Long%20Range%22&player_tc=%22AGUEROS%22&result=%22Win%22&sbMenu=%22m_ppg%22&seasons=%22Single%22&seqPlVenue=%22All%22&seqVenue=%22All%22&spanA=10&spanVenue=%22All%22&sp_pcFullGames=50&sp_pcFullGamsTeams=%22All%20Teams%22&st_boxGames=25&st_boxPositions=%5B1%2C20%5D&teamA=%22Everton%22&team_cpc=%22Tottenham%20H%22&teamD=%22West%20Ham%20U%22&teamE=%22All%20Teams%22&team_fp=%22Leicester%20C%22&tmGoals=%22For%22&twoTeams=%5B%22Chelsea%22%2C%22Tottenham%20H%22%5D&twoTeamsApp=%22Appeared%22&withClub=%22All%22&yronyrCat=%22Points%22&yronyrRound=25&yronyrTeam=%5B%22Arsenal%22%2C%22Chelsea%22%2C%22Liverpool%22%2C%22Man.%20Utd.%22%5D
> 
> If I enter this in a browser, I get sent to the front page rather than the menu I am after. If I switch to the specific menu subitem Managers > Avpoints per game, I seem to get varying outputs. However what I reall want is the output to immediately reflect what is in the image tx

Hi pssguy , glad connecting you. Wanted to check if you were able to solve this issue?
