### ISSUE TITLE
Cannot overwrite <title></title>

### ISSUE THREAD

**Issue by cinkie** [rstudio/shinydashboard#197]
When using use `tags$head(tags$title('myTitle'))` under `dashboardBody` function, the HTML webpage output is 
```
<head>
<title></title>
<title>myTitle</title>
</head>
```

A mini example from @bborgesr

```
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(tags$head(tags$title('myTitle')))
)
server <- function(input, output, session) {}
shinyApp(ui, server)
```

**Comment by bborgesr** [comment]
Thanks! This was fixed in #203. The updated code is now in the development version of shinydashboard (to install in R, do `devtools::install_github("rstudio/shinydashboard")`), which will be released to CRAN within the next couple of weeks.
