### ISSUE TITLE
Random crash when i run shinydashboard ?

### ISSUE THREAD

**Issue by Vince0931** [rstudio/shinydashboard#198]
> runApp()

Listening on http://127.0.0.1:7407

> runApp()

Listening on http://127.0.0.1:7407
Warning: Error in &&: type 'x' incorrect dans 'x && y'
Stack trace (innermost first):
    49: private$shouldSuspend
    48: .subset2(public_bind_env, "initialize")
    47: Observer$new
    46: observe
    45: .subset2(x, "impl")$defineOutput
    44: $<-.shinyoutput
    43: $<- [/Users/vincentcau/Etudes/Formulaire/R_Form/server.R#61]
    42: server [/Users/vincentcau/Etudes/Formulaire/R_Form/server.R#61]
     1: runApp
Error in hidden && private$getOutputOption(name, "suspendWhenHidden",  : 
  type 'x' incorrect dans 'x && y'
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer

> runApp()

Listening on http://127.0.0.1:7407

> runApp()

Listening on http://127.0.0.1:7407
Warning: Error in &&: type 'x' incorrect dans 'x && y'
Stack trace (innermost first):
    49: private$shouldSuspend
    48: .subset2(public_bind_env, "initialize")
    47: Observer$new
    46: observe
    45: .subset2(x, "impl")$defineOutput
    44: $<-.shinyoutput
    43: $<- [/Users/vincentcau/Etudes/Formulaire/R_Form/server.R#61]
    42: server [/Users/vincentcau/Etudes/Formulaire/R_Form/server.R#61]
     1: runApp
Error in hidden && private$getOutputOption(name, "suspendWhenHidden",  : 
  type 'x' incorrect dans 'x && y'
ERROR: [on_request_read] connection reset by peer

> runApp()

Listening on http://127.0.0.1:7407

> runApp()

Listening on http://127.0.0.1:7407

> runApp()

Listening on http://127.0.0.1:7407

> runApp()

Listening on http://127.0.0.1:7407

> runApp()

Listening on http://127.0.0.1:7407

> runApp()

Listening on http://127.0.0.1:7407

> runApp()

Listening on http://127.0.0.1:7407

> runApp()

Listening on http://127.0.0.1:7407

> runApp()

Listening on http://127.0.0.1:7407
Warning: Error in &&: type 'x' incorrect dans 'x && y'
Stack trace (innermost first):
    49: private$shouldSuspend
    48: .subset2(public_bind_env, "initialize")
    47: Observer$new
    46: observe
    45: .subset2(x, "impl")$defineOutput
    44: $<-.shinyoutput
    43: $<- [/Users/vincentcau/Etudes/Formulaire/R_Form/server.R#61]
    42: server [/Users/vincentcau/Etudes/Formulaire/R_Form/server.R#61]
     1: runApp
Error in hidden && private$getOutputOption(name, "suspendWhenHidden",  : 
  type 'x' incorrect dans 'x && y'
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer
ERROR: [on_request_read] connection reset by peer

**Comment by wch** [comment]
Are you using a development version of Shiny? This was something that came up in a development version of Shiny, but is now fixed.

**Comment by Vince0931** [comment]
i use : 
shiny 1.0.0.9001
shinydasboorad 0.5.3

I just update all packages and the problem is the same.
But I have the feeling that the problem come from the "dataTableOutput"  with the shinydashbord !

**Comment by wch** [comment]
Can you start in a clean R session, run your app, and then provide the output of `devtools::session_info()`?

**Comment by Vince0931** [comment]
> devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                                      
 version  R version 3.2.4 Revised (2016-03-16 r70336)
 system   x86_64, darwin15.3.0                       
 ui       RStudio (1.0.136)                          
 language (EN)                                       
 collate  fr_FR.UTF-8                                
 tz       Europe/Paris                               
 date     2017-03-17                                 

Packages -------------------------------------------------------------------------------------------------------------------------------------------------
 package        * version    date       source                        
 DBI            * 0.6        2017-03-09 CRAN (R 3.2.4)                
 devtools         1.12.0     2016-12-05 CRAN (R 3.2.4)                
 digest           0.6.12     2017-01-27 cran (@0.6.12)                
 DT               0.2        2016-08-09 cran (@0.2)                   
 htmltools        0.3.5      2016-03-21 CRAN (R 3.2.4)                
 htmlwidgets      0.8        2016-11-09 cran (@0.8)                   
 httpuv           1.3.3      2015-08-04 CRAN (R 3.2.4)                
 jsonlite         1.3        2017-02-28 cran (@1.3)                   
 magrittr         1.5        2014-11-22 CRAN (R 3.2.4)                
 memoise          1.0.0      2016-01-29 CRAN (R 3.2.4)                
 mime             0.5        2016-07-07 cran (@0.5)                   
 R6               2.2.0      2016-10-05 cran (@2.2.0)                 
 Rcpp             0.12.9     2017-01-14 CRAN (R 3.2.4)                
 RPostgreSQL    * 0.4-1      2016-05-08 CRAN (R 3.2.4)                
 rsconnect        0.7        2016-12-21 CRAN (R 3.2.4)                
 shiny          * 1.0.0.9001 2017-03-10 Github (rstudio/shiny@306f33d)
 shinydashboard * 0.5.3      2016-09-20 CRAN (R 3.2.4)                
 withr            1.0.2      2016-06-20 CRAN (R 3.2.4)                
 xtable           1.8-2      2016-02-05 CRAN (R 3.2.4)                
 yaml             2.1.14     2016-11-12 cran (@2.1.14)

**Comment by wch** [comment]
You need to update to a more recent version of Shiny.

**Comment by Vince0931** [comment]
Yes it work ! many thanks :)
Sorry i was thinking i was in the last version.

**Comment by lohitk27** [comment]
Listening on http://127.0.0.1:4260


Stack trace (innermost first):
    73: .local
    72: dbConnect
    71: dbConnect
    70: <reactive:main> [C:\ShinyApp\database_read\/server.R#40]
    59: main
    58: observeEventExpr
     1: runApp
Warning: Closing open result sets
Warning: Closing open result sets
Warning: Closing open result sets
Warning: Closing open result sets
Warning: Closing open result sets
Warning in .local(conn, statement, ...) :
  Decimal MySQL column 3 imported as numeric
Warning: Closing open result sets
Warning: Error in matrix: length of 'dimnames' [2] not equal to array extent
Stack trace (innermost first):
    95: matrix
    94: Ops.data.frame
    93: [<-.data.frame
    92: [<- [C:\ShinyApp\database_read\/server.R#390]
    91: <reactive:getden0> [C:\ShinyApp\database_read\/server.R#390]
    80: getden0
    79: renderUI [C:\ShinyApp\database_read\/server.R#399]
    78: func
    77: origRenderFunc
    76: output$Airden0
     1: runApp
Warning in .local(conn, statement, ...) :
  Decimal MySQL column 3 imported as numeric
Warning: Closing open result sets
Warning: Error in matrix: length of 'dimnames' [2] not equal to array extent
Stack trace (innermost first):
    101: matrix
    100: Ops.data.frame
     99: [<-.data.frame
     98: [<- [C:\ShinyApp\database_read\/server.R#525]
     97: <reactive:table> [C:\ShinyApp\database_read\/server.R#525]
     86: table
     85: inherits
     84: crosstalk::is.SharedData
     83: DT::datatable
     82: exprFunc [C:\ShinyApp\database_read\/server.R#1225]
     81: widgetFunc
     80: func
     79: origRenderFunc
     78: renderFunc
     77: origRenderFunc
     76: output$GI
      1: runApp
Warning: Error in matrix: length of 'dimnames' [2] not equal to array extent
Stack trace (innermost first):
    88: <Anonymous>
    87: stop
    86: table
    85: inherits
    84: crosstalk::is.SharedData
    83: DT::datatable
    82: exprFunc [C:\ShinyApp\database_read\/server.R#1233]
    81: widgetFunc
    80: func
    79: origRenderFunc
    78: renderFunc
    77: origRenderFunc
    76: output$power
     1: runApp
ERROR: [on_request_read] connection reset by peer
