### ISSUE TITLE
Feature request: (contextual) Help messages in navbar

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shinydashboard#2]
The current typology covers:
* messages
* notifications
* tasks

While strictly speaking it would be possible to use  *messages*  for help communications, it would be better and cleaner to have another typology for help, of course associated  with an appropriate "help" icon (the "letter" is not entirely appropriate).
An alternative would be to be able to select the icons also for the dashboard header drop down items: with an appropriate icon I could use  "messages" exclusively for (contextual) help communications.

**Comment by wch** [comment]
The AdminLTE theme, which shinydashboard uses, doesn't have a help menu type. But making the icon customizable sounds like a reasonable solution.
