### ISSUE TITLE
A first menuItem in sidebar is invisible behind the header of shinyapps.io

### ISSUE THREAD

**Issue by ksmzn** [rstudio/shinydashboard#20]
Today, I checked my Shiny app, and found that my first menuItem in sidebar is invisible behind the header of shinyapps.io.

Until yesterday:
![cursor_ _](https://cloud.githubusercontent.com/assets/4282797/6680246/c40e0920-cc97-11e4-8f2b-3ac847a160db.png)

Today:
![2015-03-17 11 15 04](https://cloud.githubusercontent.com/assets/4282797/6680249/d607280a-cc97-11e4-8e4f-e2d1b3107b5a.png)

Are there any ways to avoid this problem? 
Thanks.

**Comment by wch** [comment]
Very strange... Can you send a link to the app? If you want to keep it private, you can email me directly at winston@rstudio.com.

**Comment by ksmzn** [comment]
@wch Thanks!
This app of mine is here:
https://ksmzn.shinyapps.io/statdist/

Source:
http://github.com/ksmzn/ShinyDistributionsApp

**Comment by wch** [comment]
This looks like a bad interaction between Shinyapps.io and shinydashboard.

@kippandrew @CBarraford It looks like the shinyapps.io header doesn't work properly with shinydashboard - we'll need to figure out a way to make them play well together.

**Comment by wch** [comment]
@ksmzn We needed to make some changes to both shinydashboard and shinyapps.io, and this should work now.
