### ISSUE TITLE
tab-click makes conditional input disappear

### ISSUE THREAD

**Issue by jslul** [rstudio/shinydashboard#200]
Is there a way to disable the call that is made when a menuitem (tab) is clicked (tabName = NULL) ?. When i expand the filter menuitem and change the value, the input dissapears. 

1. Dashboard starts on selected tab 
2. Filter tab is clicked to show selectinput "choices"
3. Selectinput is changed, and then disappears

![image](https://cloud.githubusercontent.com/assets/26651906/24295546/7c0df348-109b-11e7-9a8d-5d7a8b357d4a.png) 
![image](https://cloud.githubusercontent.com/assets/26651906/24295558/919d2968-109b-11e7-97aa-95bd6c2432c2.png) 
![image](https://cloud.githubusercontent.com/assets/26651906/24295576/a81e20d4-109b-11e7-823e-59761ce7892e.png)

Example code:
```

library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(
    
    sidebarMenu(id = "tab", 
                
                #MAIN NAVIGATION 
                menuItem("Page 1", tabName = "1", icon = icon('television'), selected = TRUE),
                menuItem("Page 2", tabName = "2", icon = icon('search')),
                menuItem("Page 3", tabName = "3", icon = icon('handshake-o')),
                
                #FILTER 
                menuItem("Filter", tabName = "4", icon = icon('filter'),
                         
                         conditionalPanel("input.tab == '1'",
                                            selectInput("Choices", "Choices",
                                              choices = c(10, 20, 30)
                                          )),
                         conditionalPanel("input.tab == '2'",
                                            selectInput("Choices", "Choices",
                                              choices = c(31, 250, 320))
                                          )),
                         conditionalPanel("input.tab == '3'",
                                            selectInput("Choices", "Choices",
                                              choices = c(1440, 204, 304))
                                          ))),
  dashboardBody())
server <- function(input, output, session) {}
shinyApp(ui, server)
```

**Comment by bborgesr** [comment]
Sorry, this seems really confusing. So you have a bunch of logic for when `input$tab` is `1`, `2`or `3`. But when you change it to `input$tab = 4` (by clicking on the "Filter" menuItem), you expect that logic to still apply? `input$tab` can only have one value at any given time, so it cannot be both `2` and `4`. If it's `4`, the logic for `2` won't apply.

So:

1. don't give the "Filter" tab a `tabName`;
2. use `updateSelectInput`instead of the three conditionalPanels

Something like this:
```r
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(
    sidebarMenu(id = "tab", 
      menuItem("Page 1", tabName = "1", icon = icon('television'), selected = TRUE),
      menuItem("Page 2", tabName = "2", icon = icon('search')),
      menuItem("Page 3", tabName = "3", icon = icon('handshake-o')),
      menuItem("Filter", icon = icon('filter'),
        selectInput("choices", "Choices", character(0))
      )
    )
  ),
  dashboardBody()
)
server <- function(input, output, session) {
  observe({
    choices <- switch(input$tab,
      `1` = c(10, 20, 30),
      `2` = c(31, 250, 320),
      `3` = c(1440, 204, 304)
    )
    updateSelectInput(session, "choices", choices = choices)
  })
}

shinyApp(ui, server)
```

**Comment by jslul** [comment]
I apologize for the confusion! i failed to remove `tabName = 4`, which i used for testing. 

If i don't give "Filter" a `tabName` it produces the same result, the input disappears after a change, if "filter" was the last selected tab. It would be great if `menuItem` had an argument to make it independent of tabName. 

Using switch (with the addition of` if (!is.null(input$tab)`) worked for my purpose, thank you very much!
