### ISSUE TITLE
Dashboard body

### ISSUE THREAD

**Issue by wenbostar** [rstudio/shinydashboard#201]
Hi,

Does anyone know how to remove the part of above the tab name "home"?

<img width="509" alt="shiny_dashboard" src="https://cloud.githubusercontent.com/assets/5302110/24588661/4fa75b3e-1792-11e7-9380-0dc961176dfa.png">

Best regards!
Bo

**Comment by dmpe** [comment]
@wenbostar could you please provide minimal example to reproduce. thanks!

**Comment by wenbostar** [comment]
@dmpe ,
Below is the code. Thanks a lot.


library(shinyjs)
library("shiny")
library("shinyFiles")
library(DT)
library(shinydashboard)
library(shinythemes)
library(shinysky)
library(bsplus)
library("htmltools")

server <- function(input, output) {
    output$distPlot <- renderPlot({
        hist(rnorm(input$obs), col = "darkgray", border = "white")
    })
}

ui <- shinyUI(
    dashboardPage(
                  dashboardHeader(title = "Shiny"),
                  dashboardSidebar(),
                  
                  dashboardBody(
                      
                      fluidRow(
                          box(width = NULL,height = NULL,
                              tabsetPanel(selected = "Result",
                                          tabPanel("Home"),
                                          tabPanel("Result"),
                                          tabPanel("Help"),
                                          tabPanel("About")
                                          
                                          
                                          
                              )
                          )
                      )
                  )
    )
)

shinyApp(ui = ui, server = server)

**Comment by dmpe** [comment]
Try overwriting `.content` CSS style with `padding: 0px !important;` (i.e. add this to styles). 

But broadly speaking, i dont know if what you try to create is a good solution, in line with AdminLTE guidelines.

**Comment by bborgesr** [comment]
@dmpe's suggestion is correct. You can add the css rule directly in your app (or create a css file if you have a lot of styling to do):

```r
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(title = "Shiny"),
  dashboardSidebar(),
  dashboardBody(
    tags$head(tags$style(HTML(".content { padding-top: 0;}"))),
    fluidRow(
      box(width = NULL, height = NULL,
        tabsetPanel(selected = "Result",
          tabPanel("Home"),
          tabPanel("Result"),
          tabPanel("Help"),
          tabPanel("About")
        )
      )
    )
  )
)

server <- function(input, output, session) {}
shinyApp(ui, server)
```

Also, **questions of this sort (help with code) are better suited for the [shiny-discuss mailing list](https://groups.google.com/forum/#!forum/shiny-discuss)**. This issue tracker on Github is meant for users to report suspected bugs or suggest feature requests.
