### ISSUE TITLE
Feature Request: Dynamic sidebarMenu to accept list

### ISSUE THREAD

**Issue by dimaoo7** [rstudio/shinydashboard#23]
Similar to the dropdownMenu function, it would be great to feed sidebarMenu a list in order to dynamically generate sidebar tabs.
In the meantime, is there a workaround for adding a list of menuItems with renderMenu?

**Comment by wch** [comment]
Good idea, I just implemented it.

In general, you can pass a list as arguments to a function, with `do.call()`. So these two are equivalent:

```R
sidebarMenu(menuItem('foo'), menuItem('bar'))

do.call(sidebarMenu, list(menuItem('foo'), menuItem('bar')))
```
