### ISSUE TITLE
sidebarSearchForm - text input field and search button don't line up

### ISSUE THREAD

**Issue by jerrelsnow** [rstudio/shinydashboard#235]
When utilizing the sidebarSearchForm function, the resulting text input field and search button don't line up. See code below:
sidebarSearchForm(textId = "search_text", buttonId = "search_button", label = "Search...")

See attached screenshot.
[sidebarSearchForm output.docx](https://github.com/rstudio/shinydashboard/files/1195270/sidebarSearchForm.output.docx)

This was done under R version 3.3.3, RStudio v1.0.136 and shinydashboard v0.6.1 via IE11.

Is there some setting on the computer or in IE that would cause this?

FYI, the same behavior occurs on other browsers, like Firefox and Chrome.

Please let me know if more information is needed as this is the first time I've submitted an issue.

Thanks,
Jerrel Snow

**Comment by shosaco** [comment]
I can confirm this issue. Might be related to #240.

**Comment by bborgesr** [comment]
Thanks for the report. I've just fixed it for the development version. Let me know if you still experience any problems. The next time that `shinydashboard` is released to CRAN, this change will also take effect there.
