### ISSUE TITLE
Dynamically create number of infoboxes

### ISSUE THREAD

**Issue by deepjyot1991** [rstudio/shinydashboard#247]
Hello,

I am trying to create dynamic number of infoboxes based on the selectinput selection.
For eg.

Table has values as below:

Input | Output
a | 3
a | 6
b | 2
b | 9
b | 4
c | 6

If I select "a", then I would need 2 infoboxes to display 3 and 6.
If I select "b", then I would need 3 infoboxes to display 2, 9 and 4.
If I select "c", then I would need 1 infobox to display 6.

Is there a way to do this using Shinydashboard.

Regards,
Deepjyot.

**Comment by bborgesr** [comment]
This is definitely possible, but it is not what this issue tracker is for (only bugs and feature requests). Please submit your question to https://community.rstudio.com/c/shiny (and make sure to tag it with the `shinydashboard` tag). It will help if you include sample code (minimal reproducible example) of what you've done so far.
