### ISSUE TITLE
GPL-2 licensing

### ISSUE THREAD

**Issue by alamit** [rstudio/shinydashboard#258]
I have opened this [issue](https://github.com/ficonsulting/RInno/issues/46) on `RInno` package. 

As from what I could see, `shinydashboard` is not required to be GPL-2 only by its dependencies, would it be feasible to consider licensing `shinydashboard` under GPL-3 or GPL (>= 2)?

I think it would be more coherent as `shinydashboard` is made to run on top of `shiny` and GPL-2 is not compatible with GPL-3, but maybe I am missing a point.

**Comment by wch** [comment]
Hi, we've changed the license to GPL>=2. Thanks for notifying us about this.

**Comment by alamit** [comment]
Thank you very much, also I think you forgot to update the `LICENSE`file, which states:

> The shinydashboard package as a whole is distributed under GPL-2 (GNU GENERAL PUBLIC LICENSE version 2).

It could lead to misunderstandings, even if the official way of licensing an R package is `DESCRIPTION` file.

**Comment by wch** [comment]
Thanks, I've fixed this in ef38ca5.
