### ISSUE TITLE
Dashboard page does not include fontawesome by default.

### ISSUE THREAD

**Issue by HWGehring** [rstudio/shinydashboard#27]
When loading a vanilla dashboardPage
```
library(shinydashboard)

dashboardPage(
  dashboardHeader(title='Title'),
  dashboardSidebar(),
  dashboardBody()
)
```
fontawesome is not rendered as an html link and the menu collapse icon appears as an unknown character.

Adding a `sidebarSearchForm()` however
```
library(shinydashboard)

dashboardPage(
  dashboardHeader(title='Title'),
  dashboardSidebar(
    sidebarSearchForm(textId="search", buttonId="searchButton", label="Search...")
    ),
  dashboardBody()
)
```
will correctly trigger the link to be included.

**Comment by wch** [comment]
It looks OK to me. Can you include a screenshot? Also, are you using the latest version?

**Comment by HWGehring** [comment]
Using 0.3.0. Vanilla template, no icon:

![screen shot 2015-03-31 at 1 50 26 am](https://cloud.githubusercontent.com/assets/1647648/6913050/93e6a99e-d748-11e4-995b-49a56432067d.png)

Explicit import, loads icon:

![screen shot 2015-03-31 at 1 50 45 am](https://cloud.githubusercontent.com/assets/1647648/6913052/9998aa4a-d748-11e4-92fa-6010c6a167ad.png)

Include sidebarSearchForm, loads icon:

![screen shot 2015-03-31 at 1 52 00 am](https://cloud.githubusercontent.com/assets/1647648/6913055/9f5a614e-d748-11e4-9764-5233da368371.png)

---

And the HTML you can see font-awesome appear/disappear on line 11 depending on if sidebarSearchForm is used:

![screen shot 2015-03-31 at 1 56 38 am](https://cloud.githubusercontent.com/assets/1647648/6913099/4d1bfe1e-d749-11e4-87aa-6488dd788e1e.png)

![screen shot 2015-03-31 at 1 56 49 am](https://cloud.githubusercontent.com/assets/1647648/6913101/52a48d9c-d749-11e4-9604-cb5887d62405.png)

**Comment by wch** [comment]
Thanks - for some reason my browser was automatically getting font-awesome even with the blank page, but I did see that it was needed there.

**Comment by HWGehring** [comment]
Thanks for the quick patch, I'd do my own pull requests but I'm still new to R.
