### ISSUE TITLE
add user panel in shinydashboard

### ISSUE THREAD

**Issue by vikram-rawat** [rstudio/shinydashboard#274]
Is there a way to add tabitems in upper rightcorner of the header. I tried dropdownMenu but it didn't work. it doesn't have the functionality to add a tab button.

What should I do. please do reply

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
