### ISSUE TITLE
Can't render shinydashboard inside a renderUI

### ISSUE THREAD

**Issue by vikram-rawat** [rstudio/shinydashboard#280]
How can I create a dashboard inside a renderUI

```
library(shiny)
library(shinydashboard)

ui <-uiOutput('app')
# main_ui('some')

server <- function(input, output, session) {
    
    # callModule(mod_crud_serve,'some')
    
    output$app<-renderUI({
        dashboardPage(
            dashboardHeader(),
            dashboardSidebar(),
            dashboardBody()
        )
    })
}

shinyApp(ui, server)

```

Please help me I am trying to connect a login page with shinydashboard.

![image](https://user-images.githubusercontent.com/22342596/40612340-ae1ffa58-6297-11e8-8a93-2ad6249bab8c.png)

![image](https://user-images.githubusercontent.com/22342596/40612401-fcdbe918-6297-11e8-9850-5fd19a8e8255.png)

It doesn't throw a dashboard in renderUI to outputUI but shows me a blank page.

**Comment by wch** [comment]
Sorry, you can't put an entire `shinyDashboard()` in a `renderUI()`. You might be able to use `renderUI()` to add a div that covers the entire window, using the `position: absolute` CSS property.

**Comment by akshatha-g** [comment]
Hi wch,
I am trying to build a shiny app with multiple pages and need to render the pages from server instead of ui. One of the pages in a navbarPage and the other is a shinydashboard. Is there a way to render this from server? Any tips would help!
Thanks!

**Comment by mxfeinberg** [comment]
@akshatha-g , I am running into the same issue right now.  I'm thinking about just hosting the pages on different apps and linking them via href. @wch could you provide some more details about the work around you proposed?

**Comment by alandipert** [comment]
While it's not possible to put `shinyDashboard()` in a `renderUI()`, it *is* possible to use [shinyjs]() to toggle between different UIs on the client. In case it's helpful, an example is below.

![flip3](https://user-images.githubusercontent.com/26024/57332555-d2e0cd80-70cf-11e9-8d8f-a4d2d1c1d43d.gif)

```R
library(shiny)
library(shinydashboard)
library(shinyjs)

ui <-  tagList(
    useShinyjs(),
    div(id = "dashboard",
        style = "display:none",
        dashboardPage(
            dashboardHeader(),
            dashboardSidebar(),
            dashboardBody(actionButton("goNavbar", "Navbar Page"))
        )
    ),
    div(id = "navbarPage",
        style = "display:none",
        navbarPage("App Title",
           tabPanel(
             "Plot",
             actionButton("goDashboard", "Dashboard")
           ),
           tabPanel("Summary"),
           tabPanel("Table")
        )
    )
)


server <- function(input, output) {
    shinyjs::show("navbarPage")
    observeEvent({ input$goNavbar; input$goDashboard }, {
        shinyjs::toggle("navbarPage")
        shinyjs::toggle("dashboard")
    })
}

shinyApp(ui, server)
```

**Comment by akshatha-g** [comment]
Hi Alan,

Thanks for this tip.
Currently, my app is organized as follows

?params=a => shinydashboard
?params=b => fluidpage 1
?params=c => fluidpage 2

The 3 pages are not linked (you cannot click on any tab and land in a different ui page)
But based on the request params, we would serve a different ui page.
This was easy to do with just the fluidpage. The server would check the params and serve a different fluid page through render ui. The issue is I can't do the same with the dashboard page.

Is there a way to still use shinyjs to switch between dashboard and navbarPage like your example? 
(without the actionbutton)

**Comment by alandipert** [comment]
Hi, yes, a way to do what I think you're asking for comes to mind. Here's what it looks like:

![pages](https://user-images.githubusercontent.com/26024/57645324-ddd5ab00-7572-11e9-92ca-a031934d7124.gif)

`app.R`:
```R
library(shiny)
library(shinydashboard)
library(shinyjs)

ui <-  tagList(
  useShinyjs(),
  div(id = "page_a",
      style = "display:none",
      dashboardPage(
        dashboardHeader(),
        dashboardSidebar(),
        dashboardBody("In the dashboard page.")
      )
  ),
  div(id = "page_b",
      style = "display:none",
      navbarPage("App Title",
                 tabPanel(
                   "Plot",
                    "In the navbar page." 
                 ),
                 tabPanel("Summary"),
                 tabPanel("Table")
      )
  )
)

server <- function(input, output) {
  pages <- c("a", "b")
  observe({
    show <- getQueryString()$page
    show <- if (is.null(show)) "a" else show
    for (hide in pages[pages != show]) {
      shinyjs::hide(paste0("page_", hide))
    }
    shinyjs::show(paste0("page_", show))
  })
}

shinyApp(ui, server)
```

**Comment by akshatha-g** [comment]
Hi @alandipert This worked :) Thanks a lot for sharing this workaround.

The only issue I observed was that the window title (in tab on browser) always uses the page_a title and not the page_b title (even when page_b is shown). When i inspect the page source, this is how the title is set:

<script src="shinyjs/shinyjs-default-funcs.js"></script>
--
  | <script>shinyjs.debug = false;</script>
  | <title>Page A</title>
  | <title>Page B</title>
  | <title>

So the window title always shows up as Page A.
But the page is selected correctly based on the query params.

**Comment by alandipert** [comment]
You're welcome, it was my pleasure.

Good point about about the title &mdash; I think I was able to work around that. I updated the example, please take a look.

**Comment by akshatha-g** [comment]
This worked :) Thanks @alandipert
