### ISSUE TITLE
sidebarUserPanel(): image in www/ subdir not working

### ISSUE THREAD

**Issue by doenertier83** [rstudio/shinydashboard#29]
Installed the latest shinydashboard version using the sidebarUserPanel() argument "image" combined with .png or .jpg image in subdirectory /www within the app directory gives only "?" in the app. 

  sidebarUserPanel(name = "myname",
                   subtitle = a(href = "#", icon("circle", class = "text-success"), "Online"),
                   # Image file should be in www/ subdir
                   image = "myimage.png"))

It also doesnt matter if I give the full path image = "C:/mydir/www/myimage.png"

**Comment by wch** [comment]
Thanks for reporting. I've pushed a fix. Could you test it out?
