### ISSUE TITLE
Missing sidebar toggle icon using latest shiny version

### ISSUE THREAD

**Issue by ismirsehregal** [rstudio/shinydashboard#297]
Using the latest shiny_1.1.0.9001 (and shinydashboard_0.7.0) the sidebar toggle icon (burger icon) isn't displayed correctly:

Firefox:
![image](https://user-images.githubusercontent.com/36849480/46859713-cc76c580-ce0e-11e8-909f-39b0ceca1d94.png)

Chrome:
![image](https://user-images.githubusercontent.com/36849480/46859743-e31d1c80-ce0e-11e8-8a70-f09904c341ad.png)

Might be related to [this](https://github.com/rstudio/shiny/pull/2186)?

```
# if (!require("devtools"))
#   install.packages("devtools")
# devtools::install_github("rstudio/shiny")

## app.R ##
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
)

server <- function(input, output) { }

shinyApp(ui, server)
```

**Comment by wch** [comment]
Thanks for the report -- we're taking a look into the problem.
