### ISSUE TITLE
assign id value to sidebarMenu?

### ISSUE THREAD

**Issue by happyshows** [rstudio/shinydashboard#3]
Hi,

I am wondering if id can be assigned to the sidebarMenu so that Joe's partials framework (https://github.com/jcheng5/shiny-partials) can be applied. When I try to add id = "partial" to sidebarMenu() the console keep throwing an error below:
Error in FUN(X[[1L]], ...) : Expected an object with class 'shiny.tag'.

Please provide an example, thanks...

**Comment by ttzzhh** [comment]
Hi, 

I was wondering the same thing. I want to know if there is a way for me to tell which tab has been selected from the sidebar menu. This way, I will be able to have my sidebar inputs to change when different tabs are being selected. I tried to put two tabItems() with one in the body, one in the sidebar, 
but that did not work.

**Comment by wch** [comment]
@happyshows At the moment there isn't a way to assign an ID to a `sidebarMenu`. Sorry, I don't know the partials framework well enough to comment on your use of it. 

@ttzzhh At the moment there isn't a way to tell from the server which tab is selected, but that does sound like a useful feature.

**Comment by wch** [comment]
I added the ability to get the current tab, which also involved adding an `id` to the `sidebarMenu`.
