### ISSUE TITLE
How can I remove the googlefontapis usage?

### ISSUE THREAD

**Issue by shrektan** [rstudio/shinydashboard#32]
I'm a fun of `shinydashboard` in China. I just update the `shinydashboard` and find that it will take a very long time to load the shiny app, because it can't reach `fonts.googleapis.com` in China. **As you know, for some reasons, all the google's websites are blocked in China.**

It brings me a lot trouble, because I have to wait for minutes to load the shiny app...

Because the 360.com provides an alternative way to use the public google api, which is use `fonts.useso.com` to replace `fonts.googleapis.com`. But I don't know how. 

**Is there any easy way to do this? I think the `googleapis` is only used in http://127.0.0.1:3298/AdminLTE-2.0.6/AdminLTE.min.css.**

Thanks.

**Comment by wch** [comment]
Hi, yes, it can be fixed. I'll try to get to this in the next few days.

**Comment by shrektan** [comment]
Thanks. 

And I've found a temporary solution that is to modify related CSS files in the installed `shinydashboard` package file.
