### ISSUE TITLE
Unable to use "Run App button" in RStudio Version 1.2.1335

### ISSUE THREAD

**Issue by tpaglino** [rstudio/shinydashboard#320]
I'm having the same issue as someone posted back in 2015, however this is the newest version of R studio. I'm not exactly sure whats happening.

<img width="539" alt="Screen Shot 2019-06-14 at 1 16 20 PM" src="https://user-images.githubusercontent.com/47227686/59535861-e3425000-8ea6-11e9-8d2d-e28c1927c97b.png">

**Comment by wch** [comment]
I think this issue is more appropriate for the https://github.com/rstudio/rstudio repository.

Although... I think that it might be the intended behavior, and that you'll only see the Run App button if the file is named app.R, server.R, or ui.R.

**Comment by tpaglino** [comment]
Awesome, thank you for your help!
