### ISSUE TITLE
Random Crash while trying to run shinydashboard with a Oauth and Public Bind Issue.

### ISSUE THREAD

**Issue by Richard-Barrett** [rstudio/shinydashboard#322]
Hi guys, 

I am having two issues. Oauth flow and a public bind when one of my tabmenu items in my sidebar panel references a phpmyadmin. Here is the output:

createTcpServer: address already in use
Warning: Error in .subset2(public_bind_env, "initialize"): Failed to create server
  106: stop
  105: .subset2(public_bind_env, "initialize")
  104: WebServer$new
  103: httpuv::startServer
  102: oauth_listener
  101: oauth_authorize
  100: init_oauth2.0
   99: self$init_credentials
   98: .subset2(public_bind_env, "initialize")
   97: Token2.0$new
   96: httr::oauth2.0_token
   95: gs_auth
   94: server [/Users/richardbarret/Miradashboard/test_3/server.R#91]
   92: <Anonymous>
   86: function() {     args <- argsForServerFunc(serverFunc, shinysession)     withReactiveDomain(shinysession, {         do.call(wrapFunctionLabel(appvars$server, "server", ..stacktraceon = TRUE),              args)     }) }
   81: messageHandler
   74: handler
   68: <Anonymous>
Error in .subset2(public_bind_env, "initialize")(...) : 
  Failed to create server

**Comment by wch** [comment]
It sounds like the port that you're trying to listen on is already being used.

Please note that this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
