### ISSUE TITLE
Body Content not seen(rendered) for Multiple Menu items

### ISSUE THREAD

**Issue by rajatalpha** [rstudio/shinydashboard#325]
Hi Guys, 
I have a code where I am taking a file Input from the user and displaying that file and have 2 other tabs(Exploring Continuous variables and Categorical variables) where no content or plot can be seen even after using convertMenuItem function to regain its data-toggle and data-value attributes.
Also I need a dropdown in theses tabs to select only the Continuous or categorical variables so that I can work with them in the corresponding body of the two tabs. for eg Plotting Continuous and categorical variables differently on their respective tabs. 
Here is my code.
```r{}
library(shiny)
library(shinydashboard)
library(DT)

convertMenuItem <- function(mi,tabName) {
  mi$children[[1]]$attribs['data-toggle']="tab"
  mi$children[[1]]$attribs['data-value'] = tabName
  mi
}
UI <- dashboardPage(
      dashboardHeader(title = 'Data Exloration'),
      dashboardSidebar(
  sidebarMenu(
    convertMenuItem(menuItem("FULL Data",tabName="Data",icon=icon("table"),
                             fileInput("file","Upload CSV files",multiple=TRUE,accept=("text/comma")),
                             selectInput("vari", "Variable", 
                                         choices=colnames(values$df_data)), tabName = "Data"),
    convertMenuItem(menuItem("Continous variables",tabName="Query2",icon=icon("table"),
                             selectInput("vari1", "Variable", 
                                         choices=colnames(values$df_data[ ,!sapply(values$df_data, is.factor)]))), tabName = "Continous variables"),
    convertMenuItem(menuItem("Categorical variables",tabName="Query2",icon=icon("table"),
                             selectInput("vari2", "Variable", 
                                         choices=colnames(values$df_data[ ,sapply(values$df_data, is.factor)])), tabName = "Categorical variables"))
)
)
   dashboardBody(
     tabItems(
      tabItem(tabName="Data", tabName="Data",
            fluidRow(
              h2("A look into the Whole Dataset")
            ),  # end of 1st Fluid Row        
            
            fluidRow(
              DT::dataTableOutput("data.frame"))),
      tabItem(tabName = "Continous variables", h2("Widgets tab content")),
      tabItem(tabName = "Categorical variables", h2("Widgets tab content"))
  )
)
)
server <- function(input, output) {
  values <- reactiveValues(df_data = NULL)
  
  observeEvent(input$file, {
    values$df_data <- read.csv(input$file$datapath)
  })
  output$data.frame <-DT::renderDataTable(values$df_data)
  output$select <- renderUI({
    df <- values$df_data
    selectInput("vari1", "Select Variables:",names(values$df_data[ ,!sapply(values$df_data, is.factor)])))
    
  })
  output$select <- renderUI({
    df <- values$df_data
    selectInput("vari2", "Select Variables:",names(values$df_data[ ,sapply(values$df_data, is.factor)])))
    
  })
}
shinyApp(UI, server)
```

**Comment by rajatalpha** [comment]
@wch Please help me with this!!

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.

**Comment by rajatalpha** [comment]
This is bug In Shiny Dashboardas it loses the data-toggle and data-value attributes while rendering multiple Menuitems??

**Comment by wch** [comment]
I think the thing you're trying to do with shinydashboard is a kind of a hack since you're directly modifying the HTML that's provided from shinydashboard's functions. When I say it's a hack, I don't mean that it's a bad thing, but it is beyond what we're able to support in this issue tracker.

Also, I tried running your code but it gives a number of errors so it wasn't possible to reproduce the problem.

**Comment by rajatalpha** [comment]
Hey please find the code attached, I could render the sidemenu but can't
see the content on the tab after selecting the variable. Also if not
possible,can you please suggest another way to this.Note-Select all the
content in the file and Run it in Rstudio.
Thank You in advance
Rajat

**Comment by rajatalpha** [comment]
Hi Winston Chang,
Also find my Screenshots of the same.

**Comment by wch** [comment]
I did not receive the code or screenshots. The GitHub email proxy probably strips them out.

**Comment by rajatalpha** [comment]
[R_sample.txt](https://github.com/rstudio/shinydashboard/files/3434972/R_sample.txt)
Here Is My Code
