### ISSUE TITLE
Upload video file and use as src for tag$video

### ISSUE THREAD

**Issue by mbio16** [rstudio/shinydashboard#327]
Hello, I have a question about video in shinydashboard. I am able to upload file to server but when defining video tag there has to be src for the static file. What if the file src is known after the upload. Is there any way to change src when the is running?

**Comment by wch** [comment]
Hi, this issue tracker is meant for bug reports and feature requests. For general help questions like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
