### ISSUE TITLE
collapsible box, collapsed at application start

### ISSUE THREAD

**Issue by dfalbel** [rstudio/shinydashboard#33]
Is it possible to make a collapsible box collapsed at the application start? 

I tried to change the box class to "collapsed" using:

```{r}
box(title = "title",
    width = NULL,
    collapsible = T, 
    class = "collapsed-box")
```

But it changes the box's body class instead of the box itselft. See the results:

```{html}
<div>
  <div class="box">
    <div class="box-header">
      <h3 class="box-title">title</h3>
      <div class="box-tools pull-right">
        <button class="btn btn-box-tool" data-widget="collapse">
          <i class="fa fa-minus"></i>
        </button>
      </div>
    </div>
    <div class="box-body collapsed-box"></div>
  </div>
</div> 
```

And i love this package!

**Comment by wch** [comment]
Glad you like it! I've added a new option, `collapsed`, which allows this.

**Comment by shrektan** [comment]
I love this too!

**Comment by dfalbel** [comment]
Great, thanks!

**Comment by maxifort** [comment]
Hi, 
the collapsed option seems to disable every output that it try to render (dataTable, plots...).
I can't figure out the reason for this issue. Any ideas?

**Comment by wch** [comment]
@maxifort This should be fixed in the latest version on CRAN. If you are still having a problem, please provide a reproducible example and the output of `sessionInfo()`.

**Comment by maxifort** [comment]
Indeed, I had 3.2.0 version on CRAN. With 3.2.1 it works fine.Thanks a lot.

Maxime fortin 
Mobile : +33 6 49 85 40 83 | Fixe :  +33 9 51 61 36 39 



Date: Tue, 7 Jul 2015 18:48:49 -0700

**Comment by maxifort** [comment]
Indeed, I had 3.2.0 version on CRAN. With 3.2.1 it works fine.
Thanks a lot.
