### ISSUE TITLE
open sever error 

### ISSUE THREAD

**Issue by fjptwenger** [rstudio/shinydashboard#343]
my system is windows, use **xshell** to log in to the linux server, I run the **dashboard** on linux, the code copy from [here](http://rstudio.github.io/shinydashboard/get_started.html), but I cannot open the link from windows http://192.168.50.78:7410 ，so how can I open the server from windows?

linux shinydashboard return :Listening on http://127.0.0.1:7410    
192.168.50.78 my server ip

**Comment by wch** [comment]
I think you need to call `runApp()` with `host = "0.0.0.0".
