### ISSUE TITLE
update documentation Glyphicons link

### ISSUE THREAD

**Issue by bhogan-mitre** [rstudio/shinydashboard#359]
The documentation shows a Glyphicons link as http://getbootstrap.com/components/#glyphicons
I believe this should be update to: https://icons.getbootstrap.com/

<img width="975" alt="Screen Shot 2020-11-30 at 8 48 38 PM" src="https://user-images.githubusercontent.com/32336739/100687006-7e561080-334d-11eb-88b2-87e28e193e89.png">

I'm happy to submit a PR if you're open to it and point me to where the documentation lives.  Thanks.

**Comment by wch** [comment]
shinydashboard uses Bootstrap 3, so I think the correct link is:
https://getbootstrap.com/docs/3.4/components/#glyphicons

I believe that https://icons.getbootstrap.com/ is a separate project?

**Comment by bhogan-mitre** [comment]
Ah, thank you.  I know I've seen that page before, it was just harder to find from the link in the shinydashboard documentation.

**Comment by wch** [comment]
Fixed in 1c2dc5b. Thanks!
