### ISSUE TITLE
dropdownMenu does not drop down

### ISSUE THREAD

**Issue by bph98** [rstudio/shinydashboard#36]
I've added a dropdownMenu to the header of my page with some messages.  It shows up in the header with the selected icon and a badge that correctly states the number of messages within it.  But there is no way to get it to actually drop down.  Clicking, mouseover, etc. just highlight the icon within the header without showing the messages within it.  Would it be possible to add an example to your site that contains a dropdownMenu to help in tracking this down.  I can see in the html that the list items for the menu are populated fine.  Do you think it's an issue with the css?  Thanks!

**Comment by wch** [comment]
There's an example here:
  https://github.com/rstudio/shinydashboard/tree/gh-pages/_apps/menus
If this doesn't work for you, please let me know.

The parent directory contains all the apps for the examples in the documentation.

**Comment by bph98** [comment]
Thanks for the link.  That minimal example works, and my application using the same syntax does not.  I added pieces one at a time to the minimal example and it appears to break when a plot from metricsgraphics is included.  I can get metricsgraphics to work fine without the dropdownMenu, and vice versa, but there appears to be some issue with the interaction between the two.  I may drop metricsgraphics for now and try ggvis instead.
