### ISSUE TITLE
[Update request] The default icon for menuSubItem() "angle-double-right" is now "angles-right" in Font Awesome 6.0.0

### ISSUE THREAD

**Issue by anna-doizy** [rstudio/shinydashboard#389]
Font Awesome is now 6.0.0 and some names have changed. Especially the one for the icon that is used by default in the `menuSubItem` function: https://origin.fontawesome.com/icons/angles-right

Would you please update the default icon name in:

```r
menuSubItem(text, tabName = NULL, href = NULL, newtab = TRUE,
  icon = shiny::icon("angle-double-right"), selected = NULL)
```

Because it leads to this issue : https://stackoverflow.com/questions/32686195/shinydashboard-some-font-awesome-icons-not-working

Thank you!

**Comment by ismirsehregal** [comment]
Please see my PR here: https://github.com/rstudio/shinydashboard/pull/388

**Comment by anna-doizy** [comment]
Great! Sorry, I didn't see your PR.

**Comment by ismirsehregal** [comment]
This was just FYI - I wouldn't close the issue until it is resolved in the main branch.

**Comment by YongbingDing** [comment]
您好，丁永兵已经收到您的邮件，谢谢。

**Comment by ismirsehregal** [comment]
The latest version of {[fontawesome](https://github.com/rstudio/fontawesome/releases/tag/v0.4.0)} allows to reference icons by several of their previous names. So I guess this can be closed.
