### ISSUE TITLE
Why use unsecure AdminLTE?

### ISSUE THREAD

**Issue by flame-zh** [rstudio/shinydashboard#399]
I ask myself the following question: 
Why does shinydashboard use AdminLTE which has vulnerabilities in each of its versions: https://security.snyk.io/package/npm/admin-lte

I haven't found anything on this issue yet. Has this been fixed in the fork or simply nobody cares?

**Comment by YongbingDing** [comment]
您好，丁永兵已经收到您的邮件，谢谢。

**Comment by gadenbuie** [comment]
Hi @flame-zh, we now recommend that you use [bslib](https://rstudio.github.io/bslib) for dashboards if you want to use the latest versions of Bootstrap or if you want a dashboarding framework that isn't tied to AdminLTE.

Here are some articles that may be of interest to you:

* [Towards easy, delightful, and customizable dashboards in Shiny for R with {bslib}](https://shiny.posit.co/blog/posts/bslib-dashboards/)
* [Getting Started with Dashboards](https://rstudio.github.io/bslib/articles/dashboards/index.html)
* [Quarto Dashboards](https://quarto.org/docs/dashboards/)

**Comment by flame-zh** [comment]
Hi @gadenbuie,

thanks for your recommendations, I will definitely have a look at bslib and Quarto Dashboards.

**Comment by gadenbuie** [comment]
Thanks! I'm going to close this issue but feel free to comment if you have any more questions.
