### ISSUE TITLE
Add href to taskItem, messageItem & valueBox

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/shinydashboard#4]
First, I may just be overlooking something obvious. Is there a way to add an action to `taskItem`, `messageItem` and `valueBox` elements so that when a user taps/clicks they would go to a specific URL? If not, is there any plan for such functionality?

**Comment by hrbrmstr** [comment]
It just occurred to me I can wrap the entire `uiOutput` in an `a` tag - `a(href="http://example.org/", uiOutput("examplebox"))`.  Apologies for the momentary mind loss.

**Comment by wch** [comment]
At the moment there isn't a simple way to add a link, but that does sounds like a really useful feature, and I'll try to add that tomorrow.

**Comment by wch** [comment]
@hrbrmstr I pushed a fix for this. Could you try it out?

**Comment by hrbrmstr** [comment]
Aye. Will do so after main work duties today (or if I can sneak a few mins)

**Comment by hrbrmstr** [comment]
works _perfectly_! #ty

**Comment by wch** [comment]
Great!
