### ISSUE TITLE
Should Be able to add a title to the menu bar

### ISSUE THREAD

**Issue by chendaniely** [rstudio/shinydashboard#41]
The current area to add title/logo is limited.  It usually only provides enough space for a logo.
There should be a way to add a full text title to the right of the menubar collapse button.

This limitation is mainly due to AdminLTE, perhaps a hack can be developed in a shinydashboardExtras package?  This way new updates from AdminLTE can be easily incorporated into shinydashboard without fear of breaking the hack.

**Comment by chendaniely** [comment]
Current hack by Tobi Guennel for a project we're working on.

```r
# create a new dashboardHeader function with the ability to pass in a title

dashboardHeader <- function(..., title = NULL, disable = FALSE,title.navbar=NULL, .list = NULL) {
  items <- c(list(...), .list)
  #lapply(items, tagAssert, type = "li", class = "dropdown")

  tags$header(class = "main-header",
              style = if (disable) "display: none;",
              span(class = "logo", title),
              tags$nav(class = "navbar navbar-static-top", role = "navigation",
                       # Embed hidden icon so that we get the font-awesome dependency
                       span(shiny::icon("bars"), style = "display:none;"),
                       # Sidebar toggle button
                       a(href="#", class="sidebar-toggle", `data-toggle`="offcanvas",
                         role="button",
                         span(class="sr-only", "Toggle navigation")
                       ),title.navbar,
                       div(class = "navbar-custom-menu",
                           tags$ul(class = "nav navbar-nav",
                                   items
                           )
                       )
              )
  )
}


header <- dashboardHeader(
  title = img(src="IMAGE.png", height = "90%"),
    title.navbar=tags$div(style="color:white;text-align:left;vertical-align:middle;display:inline-block;font-size: 36px;padding-left: 20px","tests"),
    messages, # message dropdown on the right
    notifications, # notifications drowdown on the right
    tasks # tasks dropdown on the right
)
```

**Comment by chendaniely** [comment]
This hack doesn't work very well when the screen width get's smaller.  The text will shrink to fit in the space, and not actually create a new line.

May not be a problem for shorter titles, but can be an issue for larger ones.

**Comment by pssguy** [comment]
+1 for any progress on this.
 I would also like an elegant as possible option to have say email and twitter icons with relevant url links where the messageItems currently reside

**Comment by wch** [comment]
I added an example for this in the docs:
  http://rstudio.github.io/shinydashboard/appearance.html#long-titles

It's not as simple as an option to the R functions, but I think that using custom CSS is the least bad way to do it here.

**Comment by wch** [comment]
I've changed my mind and added a `titleWidth` option, so you don't need to use custom CSS. The docs have been updated to reflect this.

**Comment by chendaniely** [comment]
looks good @wch!

I'm assuming you are still able to add an image as well by using `img` tags?

**Comment by wch** [comment]
Yup, that should work.

I've just realized that adding width control in the way that I did may cause problems on mobile devices, so it might take more time to get a proper fix in there.

**Comment by chendaniely** [comment]
That seems like it can be fixed with CSS media queries.  But I'm not sure how the `dashboardHeader` handles line breaks IIRC, it doesn't like things that are taller than the current height

**Comment by wch** [comment]
Unfortunately, the standard title/sidebar width of `230px` is coded into the AdminLTE CSS. Making `width` an option with proper behavior in various screen widths would probably require manually overriding all of those instances in the CSS. :(

**Comment by wch** [comment]
OK, I think I have it straightened out, so there should be no trouble on mobile devices. I also implemented a sidebar width option.
