### ISSUE TITLE
Initially Collapsed Box Fails to Render Content when Expanded

### ISSUE THREAD

**Issue by phillc73** [rstudio/shinydashboard#42]
If a box is collapsed on initial load, the content then fails to load when the box is subsequently expanded.

Example problem code:

```R
library("shinydashboard")

header <- dashboardHeader()

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Inputs", icon = icon("bar-chart-o"), tabName = "tabOne"
    )
  )
)

body <- dashboardBody(
  tabItems(
    tabItem("tabOne",
            box(title = "Test Box One", 
                width = 12,
                status = "success", 
                solidHeader = TRUE, 
                collapsible = TRUE,
                collapsed = TRUE,
                verbatimTextOutput("boxOneText")
            )
    )
  )
)

shinyApp(
  ui = dashboardPage(header, sidebar, body),
  server = function(input, output) {
    
    output$boxOneText <- renderText({
      paste("A test designed to provoke an emotional response")
    })
    
  }
)
```
However, the following  code, with the box expanded on initial load, works fine and even after collapsing and expanding the box. The text continues to render:

```R
library("shinydashboard")

header <- dashboardHeader()

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Inputs", icon = icon("bar-chart-o"), tabName = "tabOne"
    )
  )
)

body <- dashboardBody(
  tabItems(
    tabItem("tabOne",
            box(title = "Test Box One", 
                width = 12,
                status = "success", 
                solidHeader = TRUE, 
                collapsible = TRUE,
                collapsed = FALSE,
                verbatimTextOutput("boxOneText")
            )
    )
  )
)

shinyApp(
  ui = dashboardPage(header, sidebar, body),
  server = function(input, output) {
    
    output$boxOneText <- renderText({
      paste("A test designed to provoke an emotional response")
    })
    
  }
)
```
The problem only seems to manifest itself when boxes are initially collapsed.

I have shinydashboard 0.40 installed.

**Comment by name-name** [comment]
Just ran into the same problem and had to revert to version 0.3.1 because of this :-(

**Comment by jcheng5** [comment]
This sounds like maybe just a shown or hidden event needs to be triggered?

**Comment by wch** [comment]
Yup, it just needed those events to be triggered.

For future reference, here's a streamlined test app:

```R
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Inputs", icon = icon("bar-chart-o"), tabName = "tabOne"
      )
    )
  ),
  dashboardBody(
    tabItems(
      tabItem("tabOne",
        box(title = "Test Box One", 
          status = "success", 
          solidHeader = TRUE, 
          collapsible = TRUE,
          collapsed = TRUE,
          plotOutput("plot", height = 250),
          verbatimTextOutput("boxOneText")
        ),
        box(
          actionButton("go", "Go")
        )
      )
    )
  )
)

server <-  function(input, output) {
  output$plot <- renderPlot({
    cat(paste("plotting", input$go, "\n"))
    plot(rnorm(1 + input$go), rnorm(1 + input$go))
  })
  output$boxOneText <- renderText({
    paste("Go counter:", input$go)
  })
}

shinyApp(ui, server)
```

**Comment by happyshows** [comment]
@wch 
Currently, I am wrapping a DT table inside a box. If a user click a cell, it will trigger an cell_clicked observe event to do certain operation. Now I want to put a line to 'collapse the box' at the end of observe event.
However, if I setup a session variable and use it to trigger a redraw of the box, the dt table will disappear. (I guess shiny does not allow an object to be defined twice??)

Is there any function to update the status of collapse? something like updateTabsetPanel? I'm open to alternatives too.

server.R
sess$boxFlag <- FALSE

observeEvent(input$dt_summary_cell_clicked,{
  isolate({
    if(length(cellValue <-input$dt_summary_cell_clicked) == 0) return(invisible())
    sess$boxFlag <- TRUE
  })
})

ui.R
output$ui_box <- renderUI({
  flag <- sess$boxFlag
  
  isolate({
    box(title = 'Summary', width = 12, status = 'primary', collapsible = TRUE, collapsed = flag,
        dataTableOutput('dt_summary')
    )
  })
})

Let me know if more clarification is required.

**Comment by DarioBoh** [comment]
I have the same problem but when rendering on `sidebarMenu`, am I doing anything wrong?
```

library('shiny')
library("shinydashboard")

header <- dashboardHeader()

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Inputs", icon = icon("bar-chart-o"), tabName = "tabOne",
             uiOutput('mymenu')
    )
  )
)

body <- dashboardBody(
  h3('nothing here')
)

shinyApp(
  ui = dashboardPage(header, sidebar, body),
  server = function(input, output) {


    output$mymenu <- renderUI({

      checkboxGroupInput('mymenu', 'lettersMenu',
                         letters[1:5],
                         letters[1:5])
    })
  }
)
```
