### ISSUE TITLE
How to set the width of the sidebar?

### ISSUE THREAD

**Issue by feiyangdou** [rstudio/shinydashboard#43]
Hi, 

I was wondering if I could change the width of the sidebar since there are some lengthy contents in the sidebar turn out to be truncated. Thanks!

**Comment by stanasa** [comment]
+1 to that! 
I came here to ask exactly the same question. The template is based on the AdminLTE 2 one, but I don't know how to make shiny interact with that, via CSS or otherwise. Tried specifying the width in the www/custom.css file, but I must be doing it wrong.

**Comment by stanasa** [comment]
Partial workaround described here: http://stackoverflow.com/questions/30351560/shinydashboard-dashboardsidebar-width-setting 
It *would* be nice if this would be a property setting though. As you can see, doing it manually is a bit of a hassle.

**Comment by wch** [comment]
I've added this feature. See the documentation at:
  http://rstudio.github.io/shinydashboard/appearance.html#sidebar-width
