### ISSUE TITLE
Text overflows from dashboardHeaders

### ISSUE THREAD

**Issue by Ironholds** [rstudio/shinydashboard#45]
header <- dashboardHeader(title = "Search & Discovery Data", disable = FALSE)

produces:

![this](http://ironholds.org/misc/text_overflow.png)

**Comment by wch** [comment]
I've added some documentation about how to do this at:
  http://rstudio.github.io/shinydashboard/appearance.html#long-titles

**Comment by Ironholds** [comment]
Thanks!

**Comment by wch** [comment]
Actually, I changed my mind - I added a `titleWidth` option, so you don't need to use custom CSS.

**Comment by Ironholds** [comment]
Hah! Perfect  :D
