### ISSUE TITLE
Cannot install from CRAN

### ISSUE THREAD

**Issue by stanasa** [rstudio/shinydashboard#48]
install.packages("shinydashboard") fails on R "Smooth Sidewalk" 3.1.3

> install.packages("shinydashboard")
    Warning in install.packages : 
    package ‘shinydashboard’ is not available (for R version 3.1.3)

Current workaround:
    library(devtools)
    install_github("rstudio/shinydashboard")

**Comment by wch** [comment]
It's likely that, for some platforms, CRAN is building binary packages only for R 3.2 now. You can install it with:

```R
install.packages("shinydashboard", type = "source")
```
