### ISSUE TITLE
options(scipen=N) doesn't work with dygraphs

### ISSUE THREAD

**Issue by Ironholds** [rstudio/shinydashboard#49]
If I set options(scipen=500) I still end up using scientific notation in dygraphs for numbers below that limit. Is this a dygraph bug, a non-configurable option, ...?

**Comment by wch** [comment]
Did you mean to report this in the dygraphs issue tracker?

**Comment by Ironholds** [comment]
Actually no, I'm honestly not sure if it's a dygraph's issue or a shiny-dashboard issue and thought I'd start at the top ;p. If the answer is "dygraph has all the controls over what it does" I'll move the issue there.

**Comment by wch** [comment]
Oh, I would expect that issue to be completely independent from shinydashboard.

**Comment by Ironholds** [comment]
*thumbs up*
