### ISSUE TITLE
Removing list value attribute in sidebarMenu menuSubItem

### ISSUE THREAD

**Issue by hrabel** [rstudio/shinydashboard#5]
Hi there,
This is my first question on github so I gope it is in the right place...

I've put some widgets into the sidebar sub menus but can't seem to get rid of the little double arrow icon for each widget?
I understand these sub items are a list which has value attributes and found the conspirator in this section of shinydashboard/R/dashboardSidebar.R

#' @rdname sidebarMenu
#' @export
menuSubItem <- function(text, tabName = NULL, href = NULL, newtab = TRUE) {
...
  tags$li(
    a(href = href,
      `data-toggle` = if (isTabItem) "tab",
      target = target,
#' This guy!!
      shiny::icon("angle-double-right"),
      text
    )
  )
}

How do I remove the shiny::icon("angle-double-right")????

I've got a styles.css file in my www/ folder that has the code:
li {
  list-style-type: none
}
Hoping this would cancel any list bullet mark type attributes in my shiny app, but I don't know too much about css styling...

Any help would be greatly appreciated, thanks!

**Comment by wch** [comment]
Interesting -- when I was putting it together, I had in mind that people would add text links as menu sub items, but it sounds like you're adding in other sorts of items. What kind of things are you adding in there?

**Comment by hrabel** [comment]
Cheers for the quick response,

I have two menuItems each with its own sub menu of widgets such as selectInputs, sliderInputs etc.
I was hoping to have it working so the body was just for displaying a leaflet map then you could toggle open the side bar and choose the correct menu item then the dropdown menu would be a list of widgets to adjust the map display.

The widgets in the sidebar are displaying but the shiny::icon("angle-double-right") doesn't quite work. It's sitting funnily in the top left corner above each widget so I was hoping maybe to hide that so it is just a column of widgets with no list markers if that is possible?

Also thanks heaps for this layout function, it's really cool!

**Comment by wch** [comment]
This should do the trick. It's written as in-line CSS, but you could put it in a CSS file instead. You can put this in the `dashboardBody()`:

```R
  tags$head(tags$style(HTML('
    /* Change padding of sub-menu items */
    .sidebar .sidebar-menu .treeview-menu>li>a {
      padding: 5px 5px 5px 8px;
    }

    /* Hide icons in sub-menu items */
    .sidebar .sidebar-menu .treeview-menu>li>a>.fa {
      display: none;
    }
  ')))
```

Although, I do like the ability to hide the double-arrow, so I may introduce that as an option for menuSubItem.

**Comment by wch** [comment]
I just added an option to `menuSubItem`, so you can now do `menuSubItem(arrow=FALSE)`, and skip the CSS stuff. You can still use CSS to alter the padding, though.

**Comment by hrabel** [comment]
Awesome, that looks really tidy with the widgets.
Thanks heaps!

**Comment by wch** [comment]
I changed my mind on how to make it work. Instead of `arrow`, there's `icon`. So you can do `menuSubItem(icon=NULL)` to have no icon. To use a different icon than the default, you can do `menuSubItem(icon=icon("bolt"))`.

If possible, I'd love to see the app when it's ready. It sounds pretty nice!

**Comment by hrabel** [comment]
Cool, that's amazing how you can customize the package like that.
I'll have to upload it to this site, learning the new leaflet package so may be a little while in the works just yet..
Thanks again,
Hayden
