### ISSUE TITLE
Menuitem select only once

### ISSUE THREAD

**Issue by geoHeil** [rstudio/shinydashboard#50]
Strangely these dots appear to the left side.
I can click on each tab only ONCE. This means after three clicks I cannot switch to another tab.
![__documents_development_predictr_r-stuff_geo_clusterregressionbootstrap_-_shiny](https://cloud.githubusercontent.com/assets/1694964/7918809/63beb5a4-0894-11e5-89a7-e923667ae61c.jpg)

**Comment by wch** [comment]
Can you provide a small reproducible example?

**Comment by geoHeil** [comment]
Hi here it is:

UI .r 



# This is the user-interface definition of a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#

library(shiny)
library(shinydashboard)

dashboardPage(
  dashboardHeader(title = "hello world"),
  dashboardSidebar(
    
    menuItem("foo", tabName = "foo", icon = icon("dashboard")),
    menuItem("bar", tabName = "bar", icon = icon("th")),
    menuItem("baz", tabName = "baz", icon = icon("th"))
  ),
  dashboardBody(

    tabItems(
      # First tab content
      tabItem(tabName = "foo",
              h2("asdfsd!")
      ),
              # Second tab content
      tabItem(tabName = "bar",
                      h2("To be done"),
                      infoBox("New kkkkkk", 10 * 2, icon = icon("credit-card"))
      ),
      tabItem(tabName = "baz",
                      h2("To be done"),
                      infoBox("New Orders", 10 * 2, icon = icon("credit-card"))
      )
      
  )
  )
)



server .r


# This is the server logic for a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#

library(shiny)

shinyServer(function(input, output) {

  output$distPlot <- renderPlot({

    # generate bins based on input$bins from ui.R
    x    <- faithful[, 2]
    bins <- seq(min(x), max(x), length.out = input$bins + 1)

    # draw the histogram with the specified number of bins
    hist(x, breaks = bins, col = 'darkgray', border = 'white')

  })

})

**Comment by wch** [comment]
I think you need to wrap the `menuItem`s in `sidebarMenu()`, like so:

```R
  dashboardSidebar(
    sidebarMenu(
      menuItem("foo", tabName = "foo", icon = icon("dashboard")),
      menuItem("bar", tabName = "bar", icon = icon("th")),
      menuItem("baz", tabName = "baz", icon = icon("th"))
    )
  )
```

**Comment by geoHeil** [comment]
Thanks a lot!!!
