### ISSUE TITLE
Same Box for multiple tabPanels

### ISSUE THREAD

**Issue by sahuvaibhav** [rstudio/shinydashboard#52]
How can i update the same Box for multiple tab panels.

here is my code 

fluidRow(
              tabBox(title="Input Parameters",id="ht2",height = 550,width=5,side = "right",selected= strong(p("Paired Sample")),
                     tabPanel(strong(p("Proportions")),h4("Proportions"),
                              radioButtons("prtype",h5("Tail Type"),c("Two Tail","Left Tail","Right Tail"),selected = "Two Tail"),
                              div(class="row-fluid",
                                  div(class="col-md-6",numericInput("p1", label = "p1", value = 0.2)),
                                  div(class="col-md-6",numericInput("p2", label = "p2", value = 0.3))
                              ),
                              div(class="row-fluid",
                                  div(class="col-md-6",numericInput("n1Pr", label = "n1", value = 100.0)),
                                  div(class="col-md-6",numericInput("n2Pr", label = "n2", value = 100.0))
                              ),
                              numericInput("dp", label = "dp", value = 0.0),
                              numericInput("alphaPr", label = "alpha", value = 0.05)
                     ),
                  tabPanel(strong(p("Independent Sample")),h4(p("Independent Sample")),
                           div(class = "row-fluid",
                               div(class="span4",radioButtons("itype",h5("Tail Type"),c("Two Tail","Left Tail","Right Tail"),selected = "Two Tail")),
                               div(class="span4 offset2",radioButtons("VarType",h5("Variance Type"),c("Pooled Variance","Unpooled Variance"),selected = "Pooled Variance"))
                           ),
                           #radioButtons("VarType",h5("Variance Type"),c("Pooled Variance","Unpooled Variance"),selected = "Pooled Variance"),
                           div(class="row-fluid",
                               div(class="col-md-6",numericInput("x1", label = "x1", value = 2.0)),
                               div(class="col-md-6",numericInput("x2", label = "x2", value = 1.0))
                           ),
                           div(class="row-fluid",
                               div(class="col-md-6",numericInput("s1", label = "s1", value = 1.0)),
                               div(class="col-md-6",numericInput("s2", label = "s2", value = 1.0))
                           ),
                           div(class="row-fluid",
                               div(class="col-md-6",numericInput("n1", label = "n1", value = 100.0)),
                               div(class="col-md-6",numericInput("n2", label = "n2", value = 100.0))
                           ),
                           numericInput("du", label = "du", value = 0.0),
                           numericInput("alphaI", label = "alpha", value = 0.05)
                          ), 
tabPanel(strong(p("Paired Sample")),h4(p("Paired Sample")),solidHeader=T,
                           radioButtons("ptype",h5("Tail Type"),c("Two Tail","Left Tail","Right Tail"),selected = "Two Tail"),
                           numericInput("dbar", label = "dbar", value = 0.0),
                           numericInput("D", label = "D", value = 0.0),
                           numericInput("sdbar", label = "sd", value = 1.0),
                           numericInput("nP", label = "n", value = 100.0),
                           numericInput("alphaP", label = "alpha", value = 0.05)
                  )
              )

this creates 3 tab panels in one tab box. Now i need to create one box which gets updated from each tab Panel. Please Help.

**Comment by wch** [comment]
Can you supply a working app that reproduces the issue? I'm not sure I understand the question.

Also, see the Syntax Highlighting section on [this page](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) for information about formatting code in GitHub issues.

**Comment by sahuvaibhav** [comment]
Hi,

Please find the below code for running app. The left box is a tab box which
has 3 tabs. Right box is standalone box where i will be plotting a
histogram. I want right box to be updated as i move to any tab in the left
box.


ui = dashboardPage(dashboardHeader(title = "Stats"),
                   dashboardSidebar(sidebarMenu(
                                                menuItem("Hypothesis
Testing for 2 Populations", tabName = "tabHT2",icon = icon("area-chart"))
 ),
                                                sidebarSearchForm(textId =
"searchText", label = "Search...", buttonId = "SearchButton")
                                                ),

                    dashboardBody(tabItems(
                                  tabItem(tabName="tabHT2",h2("Hypothesis
Testing for 2 Populations"),
                                          fluidRow(
                                            tabBox(title="Input
Parameters",id="ht2",height = 550,width=5,side = "right",selected=
strong(p("Paired Sample")),

 tabPanel(strong(p("Proportions")),h4("Proportions"),

radioButtons("prtype",h5("Tail Type"),c("Two Tail","Left Tail","Right
Tail"),selected = "Two Tail"),

div(class="row-fluid",

div(class="col-md-6",numericInput("p1", label = "p1", value = 0.2)),

div(class="col-md-6",numericInput("p2", label = "p2", value = 0.3))
                                                            ),

div(class="row-fluid",

div(class="col-md-6",numericInput("n1Pr", label = "n1", value = 100.0)),

div(class="col-md-6",numericInput("n2Pr", label = "n2", value = 100.0))
                                                            ),

numericInput("dp", label = "dp", value = 0.0),

numericInput("alphaPr", label = "alpha", value = 0.05)
                                                   ),

 tabPanel(strong(p("Independent Sample")),h4(p("Independent Sample")),
                                                            div(class =
"row-fluid",

div(class="span4",radioButtons("itype",h5("Tail Type"),c("Two Tail","Left
Tail","Right Tail"),selected = "Two Tail")),

div(class="span4 offset2",radioButtons("VarType",h5("Variance
Type"),c("Pooled Variance","Unpooled Variance"),selected = "Pooled
Variance"))
                                                            ),

#radioButtons("VarType",h5("Variance Type"),c("Pooled Variance","Unpooled
Variance"),selected = "Pooled Variance"),

div(class="row-fluid",

div(class="col-md-6",numericInput("x1", label = "x1", value = 2.0)),

div(class="col-md-6",numericInput("x2", label = "x2", value = 1.0))
                                                            ),

div(class="row-fluid",

div(class="col-md-6",numericInput("s1", label = "s1", value = 1.0)),

div(class="col-md-6",numericInput("s2", label = "s2", value = 1.0))
                                                            ),

div(class="row-fluid",

div(class="col-md-6",numericInput("n1", label = "n1", value = 100.0)),

div(class="col-md-6",numericInput("n2", label = "n2", value = 100.0))
                                                            ),

numericInput("du", label = "du", value = 0.0),

numericInput("alphaI", label = "alpha", value = 0.05)

                                                   ),

 tabPanel(strong(p("Paired Sample")),h4(p("Paired Sample")),solidHeader=T,

radioButtons("ptype",h5("Tail Type"),c("Two Tail","Left Tail","Right
Tail"),selected = "Two Tail"),

numericInput("dbar", label = "dbar", value = 0.0),

numericInput("D", label = "D", value = 0.0),

numericInput("sdbar", label = "sd", value = 1.0),

numericInput("nP", label = "n", value = 100.0),

numericInput("alphaP", label = "alpha", value = 0.05)
                                                   )
                                          ),
                                            box(title = "Hypothesis Testing
for 2 populations",height = 550)
                                            )
                                          )
                                  )
                                ))
                                )


server = function(input,output){}

shinyApp(ui,server)


Thanks

**Comment by wch** [comment]
Your app doesn't work when I copy and paste. Can you please provide a working example?
