### ISSUE TITLE
ValueBox not going to other line

### ISSUE THREAD

**Issue by csese** [rstudio/shinydashboard#53]
Hi, 

I would like to use a valueBox where the text is too long for the width of the box. 
Therefore, I want it to go to the next line. 
It does not work automatically so I try using \n but it does not work either. 

![image](https://cloud.githubusercontent.com/assets/10134594/8021853/fa822ea6-0c7e-11e5-8608-f8da39423b89.png)

Do you have a work around or is that possible to implement this feature in the valuebox? 

Charles

**Comment by wch** [comment]
You would have to write some custom CSS to do this, although I'm not sure the height would expand to match the text.
