### ISSUE TITLE
Can't use renderMenu with menuSubItems

### ISSUE THREAD

**Issue by Tutuchan** [rstudio/shinydashboard#54]
Hi, I might be doing something wrong but I've spent a couple hours on this and I don't see where my error could be.

Here is a basic reproducible example. When I execute this code, the app correctly shows a menuItem that can be expanded to a menuSubItem.

```r
library(shinydashboard)
sidebar <- dashboardSidebar(
  sidebarMenu(menuItem("foo",
                        menuSubItem("foo_"), tabName = "tabfoo"))
)


ui <- dashboardPage(
  dashboardHeader(),
  sidebar,
  dashboardBody()
)

server <- function(input, output) {}

shinyApp(ui, server)
```

However, when I try to do it dynamically with renderMenu : 

```r
library(shinydashboard)
library(shiny)

sidebar <- dashboardSidebar(
  sidebarMenuOutput("sbMenu")
)


ui <- dashboardPage(
  dashboardHeader(),
  sidebar,
  dashboardBody()
)

server <- function(input, output) {
  output$sbMenu <- renderMenu({
    sidebarMenu(menuItem("foo", menuSubItem("foo_"), tabName = "tabfoo"))
    })
}

shinyApp(ui, server)
```

I can see the menuItem and the arrow showing that a menuSubItem is present but it cannot be expanded. Any idea what might be causing this ?

**Comment by wch** [comment]
Thanks for the report, I've just pushed a fix.
