### ISSUE TITLE
Add icon/img to  dashboardHeader  Title ?

### ISSUE THREAD

**Issue by happyshows** [rstudio/shinydashboard#57]
Just a question, it will be helpful to user to have some linkage between image and an application.

**Comment by wch** [comment]
I'm not 100% sure what you're asking, but I think this may answer it:

```R
library(shiny)
library(shinydashboard)
# Basic dashboard page template
shinyApp(
  ui = dashboardPage(
    dashboardHeader(title = span(tagList(icon("calendar"), "Example"))),
    dashboardSidebar(),
    dashboardBody()
  ),
  server = function(input, output) { }
)
```

**Comment by happyshows** [comment]
@wch 
is there any way to show the log without leaving the tab title in chrome as <span> <i class = .....>

**Comment by happyshows** [comment]
nvm, I found the title parameter in dashboardPage would serve the purpose.

**Comment by zhanghaoyue** [comment]
@wch 
Hello, what if I want to add a image?

**Comment by happyshows** [comment]
@zhanghaoyue can you share your example? putting the logo on upper right side. I guess its a custom  floating div?

**Comment by zhanghaoyue** [comment]
@happyshows  I added logo to header title part

**Comment by of1418** [comment]
Hello @zhanghaoyue !

How have done this ? I mean to put the logo on the upper right side ? I don't a way to do it :(

Thank you

**Comment by smartinsightsfromdata** [comment]
@of1418  [here](http://stackoverflow.com/questions/31440564/adding-a-company-logo-to-shinydashboard-header/32854387?noredirect=1#comment61025476_32854387) it is explained how.

It worked for me, but I had to split my app.R in ui.R and server.R for this to work.

**Comment by zhanghaoyue** [comment]
@of1418 

dashboardPage(


dashboardHeader(title = span(img(src="Logo1.jpg", width = 190)),
