### ISSUE TITLE
Is it possible to have an example with tabsetPanel interacting with dashboardSidebar?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shinydashboard#6]
I really like shinydashboard.
On the other hand I'm a bit confused by the interaction of tabItems / tabItem and tabsetPanel / tabPanel:
I would really appreciate an example and / or some guidance on how the two sets work best together.

For example, could I build a "complex" set of tabsetPanel / tabPanel items and still drive the menu navigation from dashboardSidebar? Or using tabsetPanel prevents me to use menuItem / menuSubItem?
I have done some experimenting but it is confusing and very time consuming. It would be good to have some "best practice" example.  Thanks!

**Comment by wch** [comment]
tabsetPanel/tabPanel and tabItems/tabItem are completely separate. The former is part of the standard shiny package, and the latter is part of shinyDashboard.

There's an example of using tabItems with menuItems on the documentation site, which you've probably seen. The tabsetPanel is separate. I think it would be possible to nest it inside a tabItem, but I haven't tested it.

**Comment by smartinsightsfromdata** [comment]
Please note that the shiny dashboard website says [here](http://rstudio.github.io/shinydashboard/structure.html#body):
```
The body of a dashboard page can contain any regular Shiny content.
```
I tried to move to shiny dashboard the app I'm developing, but some things are displayed and some are not (it is complicated to extract a "simple" example: I'll do my best and post it as soon as poss.). 

As mentioned in an earlier post I would *really* like to use shiny dashboard, but to make sense for me it must be an extension of shiny.

**Comment by wch** [comment]
If you have an example, that would be helpful.
