### ISSUE TITLE
radiobuttons with inline=TRUE not wrapping in the sidebarMenu

### ISSUE THREAD

**Issue by garthtarr** [rstudio/shinydashboard#60]
In the recent CRAN update (v0.5.0) it appears that the radioButtons no longer wrap over multiple lines.  It used to be wrapping correctly in the 0.4.0.9000 github version (from a couple of days ago).  However, when I install from github now, it is an issue (even though the version number is unchanged from 0.4.0.9000). 

```r
require(shiny)
require(shinydashboard)
ui = dashboardPage(
  dashboardHeader(title="example"),
  dashboardSidebar(
    sidebarMenu(
      radioButtons("letter",label="Pick a letter, any letter:",
                   choices=letters[1:10],
                   inline=TRUE)
    )
  ),
  dashboardBody(
  )
)
server = function(input, output) {
}
shinyApp(ui, server)
```

Not a huge issue, I can just set `inline=FALSE`, but the wrapping was a nice space saver.

For an example of how it used to work, see under "Model Stability" menuItem [here](http://garthtarr.com/apps/mplot/).  (Thinking about this specific example, I should probably be using `selectInput`, but the general issue holds.)

**Comment by wch** [comment]
Shoot, that's a probably has something to do with the updated version of AdminLTE, which has some new CSS. I'll take a look.

Also, I just pushed version 0.5.0 to github (it was just on my local machine).
