### ISSUE TITLE
menuItem and menuSubItem won't allow periods in tabitem

### ISSUE THREAD

**Issue by daltonhance** [rstudio/shinydashboard#66]
This is a bit of an odd one and probably not a big deal as long as the user is aware of it, but I found that my menuSubItems were not displaying their content if I included a period in the tabName. I've replaced with underscores, but only have twenty minutes of head-scratching.

Example:

    library(shiny)
    library(shinydashboard)
    
    header <- dashboardHeader()
    
    sidebar <- dashboardSidebar(
      sidebarMenu(
        # Setting id makes input$tabs give the tabName of currently-selected tab
        id = "tabs",
        menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
        menuItem("Widgets", icon = icon("th"), tabName = "widgets.tab", badgeLabel = "new",
             badgeColor = "green"),
        menuItem("Charts", icon = icon("bar-chart-o"),
                 menuSubItem("Sub-item 1", tabName = "subitem.1"),
                 menuSubItem("Sub-item 2", tabName = "subitem_2")
        )
      )
    )

    body <- dashboardBody(
      tabItems(
        tabItem("dashboard",
                div(p("Dashboard tab content"))
        ),
        tabItem("widgets.tab",
                "Widgets tab content"
        ),
        tabItem("subitem.1",
                "Sub-item 1 tab content"
        ),
        tabItem("subitem_2",
                "Sub-item 2 tab content"
        )
      )
    )

    shinyApp(
      ui = dashboardPage(header, sidebar, body),
      server = function(input, output) { }
    )

**Comment by smouksassi** [comment]
This is because of the underlying Javascript.

**Comment by wch** [comment]
Yes, this happens because of the way Javascript uses periods. I'll add a bit of validation to the functions here so that it will throw an error if a period is present.
