### ISSUE TITLE
Issues with shinydashboard and rhandsontable in a box

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/shinydashboard#67]
I've reported the problem on the `rhandsontable` github page by @jrowen [here](https://github.com/jrowen/rhandsontable/issues/21), but as this highlights a difference in behaviour between `shiny` and `shinydashboard`, it would be good to have somebody at rstudio to have a look as well.

The specific is that creating a box with `rhandsontable`, the widget shows the following behaviour:
- no ability to work with box defaults horizontally or vertically: `width` and `height` become a must.
- especially with no fixed height specified the box become "unacceptably" really deep, far beyond the table's size. For any practical purpose `height` is no longer optional but very much mandatory.  This does not happen in `shiny`.

This is the sample code:

``` R
library(shiny)
library(shinydashboard)
library(rhandsontable)


header <- dashboardHeader()

sidebar <- dashboardSidebar()

body <- dashboardBody(

          fluidRow(
            box(plotOutput("plot1")),
            box( title = "Controls", width=3,sliderInput("slider", "Number of observations:", 1, 10, 5) )),
          fluidRow( box(title = "Handsontable",rHandsontableOutput("hot") )

))

ui <- dashboardPage(header, sidebar, body)


server <- function(input, output) {

  set.seed(122)
  histdata <- rnorm(500)

  values  <-  reactiveValues()
  setHot  <-  function(x) values[["hot"]]  <-  x


  output$plot1 <- renderPlot({
    data <- histdata[seq_len(input$slider)]
    hist(data)
  })


  output$hot = renderRHandsontable({
  if (!is.null(input$hot)) {
    DF  <-  hot_to_r(input$hot)
    setHot(DF)
    rhandsontable(DF) %>%
      hot_table(highlightCol = TRUE, highlightRow = TRUE)
  } else {
    DF  <-  mtcars
    cols <- colnames(DF)
    DF$brand <- row.names(mtcars)
    DF <- DF[,c("brand", cols)]
    rhandsontable(DF, rowHeaders=FALSE) %>%
      hot_table(highlightCol = TRUE, highlightRow = TRUE) %>%
      hot_cols(columnSorting = TRUE, fixedColumnsLeft=1) %>%
      hot_validate_numeric(col = "mpg", allowInvalid=FALSE)
  }
  })
}

shinyApp(ui, server)
```

**Comment by wch** [comment]
Has this been fixed from the rhandsontable side of things?

**Comment by jrowen** [comment]
I believe so. I'm planning to push an update to CRAN soon.
