### ISSUE TITLE
UI input change depending on another object selection defined inside UI input

### ISSUE THREAD

**Issue by BalaramPanda** [rstudio/shinydashboard#68]
Hi,
I want to access a particular Directory, and a file from that selected directory. Then need to pass that file to Server.R for further operation. If user choose Directory_1, then on the file tab, user should able to view all the files mentioned in that Directory_1, and choose file1, and able to access file1 from Server.R
I have tried the below approach, But I am not getting the desired result. Could you please suggest some way to resolve this issue.

Code: 
=================

header <- dashboardHeader(title="TEST_IO")
sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("DIR", icon = icon("dashboard"),selectInput("DIR_ID", 
                                                            label = "DIR_ID",choices = (as.list(substr(list.dirs(paste0("D:/BW/test")),start= 12,stop=15))))),  
    menuItem("FILE", icon = icon("dashboard"),
             conditionalPanel(condition = "input.DIR_ID == TRUE",
                              selectInput("FILE_ID",label = "FILE_ID",choices = (as.list(substr(list.files(paste0("D:/BW/test/","input.DIR_ID","/")),start= 1, stop=1))))))
  )
)
body <- dashboardBody(textOutput("text1"))
ui <- dashboardPage(header, sidebar, body)
server = function(input, output){
  output$text1 <- renderText({paste("You have selected Drirectory as", input$DIR_ID,"/",input$FILE_ID)})
  
  }
shinyApp(ui,server)

![test](https://cloud.githubusercontent.com/assets/13269750/8671360/0bc2b88a-2a42-11e5-8639-95fe9e5967d3.png)

**Comment by BalaramPanda** [comment]
After choosing the directory , there is nothing visible on the File dropdown

**Comment by wch** [comment]
This sounds like a general Shiny question, which is best sent to the [shiny-discuss](https://groups.google.com/forum/#!forum/shiny-discuss) list.
