### ISSUE TITLE
sidebarUserPanel not showing after latest update

### ISSUE THREAD

**Issue by tobiasg82** [rstudio/shinydashboard#70]
It seems like the sidebarUserPanel is not showing up correctly anymore with v0.5. It worked fine with previous versions.
Here is a minimal example:

```
library(shiny)
library(shinydashboard)
ui <- dashboardPage(
  dashboardHeader(title = "Dynamic sidebar"),
  dashboardSidebar(
    sidebarUserPanel(name="Welcome back User!",subtitle = "Test",image = NULL),
    sidebarMenu(
      menuItemOutput("menuitem")
    )
  ),
  dashboardBody()
)

server <- function(input, output) {
  output$menuitem <- renderMenu({
    menuItem("Menu item", icon = icon("calendar"))
  })
}

shinyApp(ui, server)
```

Here is my sessionInfo():
```
R version 3.1.3 (2015-03-09)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.12.1         shinydashboard_0.5.0

loaded via a namespace (and not attached):
[1] digest_0.6.8    htmltools_0.2.6 httpuv_1.3.2    jsonlite_0.9.16
[5] mime_0.3        R6_2.1.0        Rcpp_0.11.6     tools_3.1.3    
[9] xtable_1.7-4   
```

**Comment by daniel-matthews** [comment]
+1, although not only limited to the latest release.

**Comment by wch** [comment]
This was due to a change in AdminLTE. I've added a fix for it in shinydashboard, but note that because of the way AdminLTE works, it will allocate space for the user image even if you're not using one:

![image](https://cloud.githubusercontent.com/assets/86978/8882198/c6b22e80-320a-11e5-9052-f397a6333dc0.png)

**Comment by daniel-matthews** [comment]
I've just updated to the github version and I still don't see it correctly (I see the image but no text). I can see the text in the html and the change you made is definitely there in the css.

**Comment by ziyadsaeed** [comment]
@daniel-matthews are you referring to this issue https://github.com/rstudio/shinydashboard/issues/75#issuecomment-137207107
