### ISSUE TITLE
Error in shinydashboard in UI

### ISSUE THREAD

**Issue by Rahul15** [rstudio/shinydashboard#72]
I am running this following script and getting problem

shinyApp(
  ui = dashboardPage(
    dashboardHeader(
      title = "Title and sidebar 350 pixels wide",
      titleWidth = 350
    ),
    dashboardSidebar(
      width = 350,
      sidebarMenu(
        menuItem("Menu Item")
      )
    ),
    dashboardBody()
  ),
  server = function(input, output) { }
)

Error:
[1] 350
Error in FUN(X[[i]], ...) : Expected an object with class 'shiny.tag'.

My  session info is as follows
R version 3.2.1 (2015-06-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_IN       LC_NUMERIC=C         LC_TIME=en_IN       
 [4] LC_COLLATE=en_IN     LC_MONETARY=en_IN    LC_MESSAGES=en_IN   
 [7] LC_PAPER=en_IN       LC_NAME=C            LC_ADDRESS=C        
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_IN LC_IDENTIFICATION=C 

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] bit_1.1-12           digest_0.6.8         dplyr_0.4.2         
 [4] RColorBrewer_1.1-2   corrplot_0.73        DMwR_0.4.1          
 [7] fields_8.2-1         maps_2.3-9           spam_1.0-1          
[10] mice_2.22            Rcpp_0.11.6          Hmisc_3.16-0        
[13] ggplot2_1.0.1        Formula_1.2-1        survival_2.38-3     
[16] lattice_0.20-31      beanplot_1.2         sm_2.2-5.4          
[19] shinydashboard_0.4.0 shinythemes_1.0.1    shiny_0.12.1        

loaded via a namespace (and not attached):
 [1] class_7.3-13        zoo_1.7-12          gtools_3.5.0       
 [4] assertthat_0.1      mime_0.3            R6_2.0.1           
 [7] plyr_1.8.3          acepack_1.3-3.3     gplots_2.17.0      
[10] gdata_2.17.0        TTR_0.22-0          rpart_4.1-10       
[13] proto_0.3-10        splines_3.2.1       stringr_1.0.0      
[16] foreign_0.8-65      munsell_0.4.2       httpuv_1.3.2       
[19] htmltools_0.2.6     tcltk_3.2.1         nnet_7.3-10        
[22] gridExtra_0.9.1     randomForest_4.6-10 MASS_7.3-43        
[25] bitops_1.0-6        DBI_0.3.1           jsonlite_0.9.16    
[28] xtable_1.7-4        gtable_0.1.2        magrittr_1.5       
[31] scales_0.2.5        KernSmooth_2.23-15  quantmod_0.4-4     
[34] stringi_0.5-5       ROCR_1.0-7          reshape2_1.4.1     
[37] latticeExtra_0.6-26 xts_0.9-7           tools_3.2.1        
[40] parallel_3.2.1      abind_1.4-3         colorspace_1.2-6   
[43] cluster_2.0.2       caTools_1.17.1

From previous issue I got that it has packages dependency problem, I have updated most of the packages still the problem persist. Any help could be very useful. 
Thanking you in advance.

**Comment by wch** [comment]
You need to update to shinydashboard 0.5.0.

**Comment by Rahul15** [comment]
I have updated the shinydashboard version to latest, but still the problem persist

Listening on http://127.0.0.1:6831
[1] 350
Error in FUN(X[[i]], ...) : Expected an object with class 'shiny.tag'.

My session info 

R version 3.2.1 (2015-06-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_IN       LC_NUMERIC=C         LC_TIME=en_IN       
 [4] LC_COLLATE=en_IN     LC_MONETARY=en_IN    LC_MESSAGES=en_IN   
 [7] LC_PAPER=en_IN       LC_NAME=C            LC_ADDRESS=C        
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_IN LC_IDENTIFICATION=C 

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] bit_1.1-12           digest_0.6.8         dplyr_0.4.2         
[4] beanplot_1.2         sm_2.2-5.4           shinythemes_1.0.1   
[7] shinydashboard_0.5.0 shiny_0.12.1        

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6     assertthat_0.1  mime_0.3        R6_2.1.0       
 [5] xtable_1.7-4    jsonlite_0.9.16 DBI_0.3.1       magrittr_1.5   
 [9] tools_3.2.1     parallel_3.2.1  httpuv_1.3.2    tcltk_3.2.1    
[13] htmltools_0.2.6

**Comment by wch** [comment]
I think you must have some strange invisible characters in your app, which is what causes it to return `[1] 350` before the code is fully processed. Try copying and pasting this into a new R session:

```R
library(shiny)
library(shinydashboard)
shinyApp(
  ui = dashboardPage(
    dashboardHeader(
      title = "Title and sidebar 350 pixels wide",
      titleWidth = 350
    ),
    dashboardSidebar(
      width = 350,
      sidebarMenu(
        menuItem("Menu Item")
      )
    ),
    dashboardBody()
  ),
  server = function(input, output) { }
)
```

**Comment by Rahul15** [comment]
Thanks. It works for me.

**Comment by KafeelBasha** [comment]
Hello,

I am trying to do text analytics inside shinydashboard and I am getting below error.
![image](https://user-images.githubusercontent.com/22866208/43761981-54661120-9a44-11e8-925a-6bd092842bb4.png)
Below are the codes used in server part.
library(shinydashboard)
library(dplyr)
library(shiny)
library(ggplot2)
server <- shinyServer(function(input,output,session){
  
  # read file
  values <- reactive({read.csv(input$file$datapath,na.strings=c(" ","","  ","   ")) })
  
  
  # observeEvent for input$file
  observeEvent(input$file, {
    
    # render tables at file upload
    output$data.frame <- renderTable(values())
    
    # update selectInput#Question
    updateSelectInput(
      session, 
      inputId = "Question",
      choices=names(values()),    
      selected=names(values()[,1])
    )
    
  })
  
  # observeEvent for input$Go
  observeEvent(input$Go, {
    # temp <- values([-input$Delete, ]    # commented for now
    # values <- temp                      # commented for now
    
    # commented for now
    library(tm)
    demo=Corpus(VectorSource(values()[,input$Question]))
    demo=tm_map(demo,content_transformer(tolower))
    demo=tm_map(demo,removePunctuation)
    df<- data.frame(text=unlist(sapply(demo,`[`)),stringsAsFactors=F)
    df$text=ifelse(df$text=="poor"|df$text=="fair","BAD",ifelse(df$text=="excellent"|df$text=="good","GOOD",NA))
    
    output$pos <- renderValueBox({
      
      # evaluate data: count, summarize, etc.
      positive<- df%>%
        filter(text=="GOOD") %>%count()    
      
      # make value box
      valueBox(positive,"Positive Response")
    })
    
    output$neg <- renderValueBox({
      
      # evaluate data: count, summarize, etc.
      negative<- df%>%
        filter(text=="BAD") %>%count()     
      
      # make value box
      valueBox(negative,"Negative Response")
    })
    
    output$nrow <- renderValueBox({
      
      #Number of records
      records<- nrow(df)
      # make value box
      valueBox(records,"Total number of responses")
    })
    
    output$bar <- renderPlot({
      
      #Bar chart
     ggplot(data=df,aes(text,fill=text))+geom_bar(aes(y = (..count..)/sum(..count..)))+geom_text(aes(y = ((..count..)/sum(..count..)), label = scales::percent((..count..)/sum(..count..))), stat = "count", vjust = -0.25)+xlab("Selected Feedback")+ylab("Response Proportion")
    })
    
    output$JigID<-renderTable({
      #Students who have given bad feedback
      values()[which(df[,"text"]=="BAD"),"sis_id"]
    })
    
  })
  
  observeEvent(input$Go,{
  #Text analytics
  library(tm)
  feeds.corpus<-Corpus(VectorSource(values()$Final))
  
  #Data Transformations -Cleaning
  feeds.corpus<-tm_map(feeds.corpus,tolower) #Converting to lower case
  feeds.corpus<-tm_map(feeds.corpus,stripWhitespace) #Removing extra white space
  feeds.corpus<-tm_map(feeds.corpus,removePunctuation) #Removing punctuations
  feeds.corpus<-tm_map(feeds.corpus,removeNumbers) #Removing numbers
  my_stopwords<-c(stopwords('english')) #Can add more words apart from standard list
  feeds.corpus<-tm_map(feeds.corpus,removeWords,my_stopwords)
  
  pos=c("good","very","best","satisfied","happy","excellent","nice","awesome","really","appreciate","easy","easier","precise","understand")
  neg=c("missed","lost","late","don't","not","tougher","difficult","bad","doesn't","difficulty","concern","uptick")
  
  #Famous Jeffreybreen Algorithm to "Tag" sentiments to sentences
  
  score.sentiment = function(sentences, pos.words, neg.words, .progress='none')
  {
    require(plyr)
    require(stringr)
    
    #we got a vector of sentences. plyr will handle a list
    #or a vector as an "l" for us
    #we want a simple array of scores back, so we use
    #"l" + "a" + "ply" = "laply":
    scores = laply(sentences, function(sentence, pos.words, neg.words) {
      
      #clean up sentences with R's regex-driven global substitute, gsub():
      sentence = gsub('[[:punct:]]', '', sentence) #removes punctuations
      sentence = gsub('[[:cntrl:]]', '', sentence) #removes control characters
      sentence = gsub('\\d+', '', sentence) #removes digits
      
      #and convert to lower case:
      sentence = tolower(sentence)
      
      #split sentences into words. str_split is in the stringr package
      word.list = str_split(sentence, '\\s+')
      
      #sometimes a list() is one level of hierarchy too much
      words = unlist(word.list)
      
      #compare our words to the dictionaries of positive & negative terms
      pos.matches = match(words, pos.words)
      neg.matches = match(words, neg.words)
      
      #match() returns the position of the matched term or NA
      #we just want a TRUE/FALSE:
      pos.matches = !is.na(pos.matches)
      neg.matches = !is.na(neg.matches)
      
      #and conveniently enough, TRUE/FALSE will be treated as 1/0 by sum():
      score = sum(pos.matches) - sum(neg.matches)
      
      return(score)
    }, pos.words, neg.words, .progress=.progress )
    
    scores.df = data.frame(score=scores, text=sentences)
    return(scores.df)
  }
  feeds.score<-score.sentiment(values()$Final, pos, neg, .progress="text")
  
  feeds.score$text<-as.character(feeds.score$text)
  feeds.score$sentiment<-ifelse(feeds.score$score>0,"positive",
                                ifelse(feeds.score$score<0,"negative","neutral"))
  #Classified feeds
  output$class_pos=renderValueBox({
    feeds.score%>%filter(sentiment=="positive")%>%count()
  })
  output$class_neg=renderValueBox({
    feeds.score%>%filter(sentiment=="negative")%>%count()
  })
  output$class_neu=renderValueBox({
    feeds.score%>%filter(sentiment=="neutral")%>%count()
  })
  })
  })

Please let me know where I am going wrong.
