### ISSUE TITLE
Feature request: Keep the sidebar icons when minimized

### ISSUE THREAD

**Issue by daniel-matthews** [rstudio/shinydashboard#74]
Not an issue but a request. I'm sure I cant achieve this with custom CCS but so far no luck. 

Would it be possible to copy the sidebar behavior from https://almsaeedstudio.com/AdminLTE whereby the sidebar remains but as icons? 

Thanks.

**Comment by FrissAnalytics** [comment]
if possible I would like to see this as well, perhaps as an optional argument...

**Comment by maxmoro** [comment]
+1 for me..

**Comment by wch** [comment]
This is a duplicate of #73.
