### ISSUE TITLE
d3heatmap incompatability

### ISSUE THREAD

**Issue by daniel-matthews** [rstudio/shinydashboard#75]
Using rstudio/d3heatmap in a box on a dashboard page causes the text in sidebarUserPanel to disappear. No idea why (probably something silly I'm overlooking), but I've removed everything else and its definitely caused by d3heatmap. Will report back if I figure out why!

**Comment by daniel-matthews** [comment]
example:

```
library(shiny)
library(d3heatmap)
library(shinydashboard)
ui <- dashboardPage(
  dashboardHeader(title = "Dynamic sidebar"),
  dashboardSidebar(
    sidebarUserPanel(name="Welcome back User!",subtitle = "Test",image = NULL),
    sidebarMenu(
      menuItemOutput("menuitem")
    )
  ),
  dashboardBody(d3heatmapOutput('sector_tab_correlation_plot'))
)

server <- function(input, output) {
  
  output$sector_tab_correlation_plot <- renderD3heatmap({
    x<-cor(mtcars,use="pairwise.complete.obs")
    d3heatmap(x, colors = "Greens",na.rm=TRUE,  scale = "column", dendrogram = "none")
  })
  
  output$menuitem <- renderMenu({
    menuItem("Menu item", icon = icon("calendar"))
  })
  
}

shinyApp(ui, server)
```

**Comment by ziyadsaeed** [comment]
there is a problem with current version of dashboard. Even the examples in dashboard don't work. 
I have removed all mention of d3heatmap from your code and the Welcome back text is shown but clipped.

**Comment by ziyadsaeed** [comment]
```R
sidebarUserPanel(name="Welcome back User!")
```
This create a div with class "info". 
```HTML
<div class="user-panel">
  <div class="pull-left info">
    <p>Welcome back User!</p>
  </div>
</div> 
```
Incidentally this same class is available in heatmap.css and AdminLTE.min.css. This is where the conflict is. heatmap.css is overwriting info class with it's own properties

**Comment by bborgesr** [comment]
This is now fixed in the development version of d3heatmap (to install, use `devtools::install_github("rstudio/d3heatmap")`). There's no current plan for when this may be released to CRAN though, so in order to avoid this issue, I'm afraid that you'll need to use the development version of d3heatmap.
