### ISSUE TITLE
feature request: animated sidebar

### ISSUE THREAD

**Issue by FrissAnalytics** [rstudio/shinydashboard#79]
in the original template at https://almsaeedstudio.com/preview the sidebar animates into the page when clicked on the menu hide/show item in the top header. Would it be possible to add this? Even though it is only stylistic, it makes the apps look a bit more pro. Thanks in advance!

**Comment by wch** [comment]
I actually specifically disabled those transitions because they were previously too bouncy and distracting. It looks like they've been toned down in AdminLTE, though, so it might make sense to re-enable them.
