### ISSUE TITLE
Is it possible to dynamically switch menuItems or menuSubItems

### ISSUE THREAD

**Issue by pssguy** [rstudio/shinydashboard#80]
I have a sports app with team and player menuItems with , say, tabName="team", tabName="player"
On the team page I have a datatable which includes a column of player names
When I click on  a specific player, I can use
 
    observeEvent(input$myTable_rows_selected,{
    # some code
    })
to collect and process the data I want to produce table/charts for the player selected
However, I also would like to switch automatically to the player page rather than relying on the user to select it. Is there a way to do this? For example, by somehow setting 
menuItem("Player Summary",tabName = "player", selected = TRUE)

I should add, that this is a very simplified example. The real-life app has lots of subMenuItems so would ideally like to avoid renderMenu approach but would also want to set whichever tab I was currently on to automatically be deselected

**Comment by Tutuchan** [comment]
Have you tried using `updateTabItems` ?

**Comment by pssguy** [comment]
@Tutuchan 

I have now. Thanks. 
I had used updateSelectInput from the Shiny package , but not noticed the one update function in shinydashboard
