### ISSUE TITLE
conditionalPanel method doesn't work with dynamically rendered sidebarMenu

### ISSUE THREAD

**Issue by yipcma** [rstudio/shinydashboard#86]
Applying the method mentioned in #28 the conditionalPanel method doesn't seem to work when the sidebarMenu is rendered dynamically. Thoughts? More specifically, I'm trying to do access control using renderMenu:
Question 1: would there be a way to make conditionalPanel work with a dynamically rendered sidebarMenu?
Question 2: is there a better way to do access control? I'm using a method akin to http://withr.me/authentication-of-shiny-server-application-using-a-simple-method/
Thank you in advance.

**Comment by Pauline6010** [comment]
Having the same issue. Did you find any solution ?

**Comment by bborgesr** [comment]
It's highly likely that there was a change that corrected this behavior over the last year (since it's been a while, sorry!), and this does seem to be working now (code adapted from #28, works equally well with a dynamic sidebar menu):

```r
library(shiny)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(
    sidebarMenuOutput("menu"),
    sliderInput("x", "Outside of menu", 1, 100, 50)
  ),
  dashboardBody()
)

server <- function(input, output, session) {
  
  output$menu <- renderMenu({
    sidebarMenu(id = "tabs",
      menuItem("A", tabName = "a",  icon = icon("group", lib="font-awesome")),
      menuItem("B", tabName = "b", icon = icon("check-circle", lib = "font-awesome")),
      conditionalPanel("input.tabs === 'b'",
        sliderInput("b", "Under sidebarMenu", 1, 100, 50)
      )
    )
  })
}

shinyApp(ui, server)
```
