### ISSUE TITLE
selected = T doesn't work with dynamically generated menuItem or menuSubItem

### ISSUE THREAD

**Issue by yipcma** [rstudio/shinydashboard#87]

**Comment by rwutzke** [comment]
Same here.. Any workaround / fix yet?

**Comment by danwwilson** [comment]
Issue #71 describes a similar scenario in more detail and with code examples.

**Comment by bborgesr** [comment]
Fixed in #199

**Comment by sanjmeh** [comment]
this issues doesn't seem to be closed, as I am facing the same problem in my code.
selected=T has no effect and the main panel remains blank unless a sidebar menuitem is manually selected.
