### ISSUE TITLE
Publishing app on Shinyapps.io

### ISSUE THREAD

**Issue by karstenthansen** [rstudio/shinydashboard#9]
I'm having trouble publishing a shinydashboard app to Shinyapps.io. I'm getting the error:

>Preparing to deploy application...DONE
>Uploading application bundle...DONE
>Deploying application: 30514...
>Error: /v1/applications/30514/deploy 400 - Unable to deploy application-30514. bundle-122840 not found.

Has anyone been successful in publishing an app using shinydashboard?

**Comment by wch** [comment]
The demo apps (like https://winston.shinyapps.io/buses) are on shinyapps.io. I think this may be an issue with shinyapps.io, not shiydashboard. Could you post [here](https://github.com/rstudio/shinyapps/issues)?

**Comment by karstenthansen** [comment]
Thanks - will do
