### ISSUE TITLE
Adding help text in sidebar menue

### ISSUE THREAD

**Issue by mubashirqasim** [rstudio/shinydashboard#90]
Hi there, 

Is it possible to add some dynamic helptext on the side bar menu. For example, I would like to add update date at the bottom of the sidebar menu.

Many thanksm

**Comment by bborgesr** [comment]
Sorry, we only got to this issue now. If this is still relevant to you, could you elaborate on what you mean?

**Comment by wch** [comment]
You can use `sidebarMenuOutput` for dynamic content. For example, this will show the time and update it every second:


```R
library(shiny)
library(shinydashboard)
ui <- dashboardPage(
  dashboardHeader(title = "Dynamic sidebar"),
  dashboardSidebar(
    sidebarMenuOutput("menu")
  ),
  dashboardBody()
)

server <- function(input, output) {
  output$menu <- renderMenu({
    # Invalidate (and re-run) this code once every second
    invalidateLater(1000)
    
    sidebarMenu(
      menuItem(Sys.time())
    )
  })
}

shinyApp(ui, server)
```
