### ISSUE TITLE
'diamond' icon not showing correctly?

### ISSUE THREAD

**Issue by happyshows** [rstudio/shinydashboard#94]
dashboardHeader(title = span(tagList(icon("diamond",class='fa-lg'), 'Icon not showing'))

**Comment by dmpe** [comment]
#110 Most probably the same issue. @happyshows Please, try to upgrade to the newer shiny version, which is on github not on CRAN.

**Comment by wch** [comment]
This works now. It was probably due to an older version of Font-Awesome previously being included with Shiny.

```R
ui <- dashboardPage(
  dashboardHeader(title = span(tagList(icon("diamond",class='fa-lg'), 'Icon not showing'))),
  dashboardSidebar(),
  dashboardBody()
)

server <- function(input, output) { }

shinyApp(ui, server)
```
